### ISSUE TITLE
Doubling channels before pooling

### ISSUE THREAD

**Issue by alexklibisz** [ellisdg/3DUnetCNN#10]
Hello, 

Looking at your code in `model.py`, it seems that you overlooked this statement on page 4 of the Cicek paper:

> Like suggested in [13] we avoid bottlenecks by doubling the number of channels already before max pooling. We also adopt this scheme in the synthesis path.

I annotated the figure below: 

![image](https://cloud.githubusercontent.com/assets/8015228/25618514/375022b0-2f15-11e7-899d-b860d0d1d080.png)

I believe this wasn't the case in 2D UNet, so it's likely a copy-paste artifact. I'm not sure what difference it will make in terms of performance, but I figured it's worth mentioning.

**Comment by ellisdg** [comment]
Nice catch!
Does #12 fix the issue?

**Comment by alexklibisz** [comment]
Thank you. It does for the downward pass (i.e. left side of figure). However the bottom "block" should be Pool -> Conv 256 -> Conv 512. It's not apparent in the paper or figure, but if you look at the prototxt you'll see it. It's also helpful to visualize the prototxt, [which you can do here](http://ethereon.github.io/netscope/#/gist/73a588aaba9b845100600878e8a1fa40). 

I might submit a PR later today that fixes it. That being said - I'm not sure if it will improve performance. So it goes with deep nets. :)
