### ISSUE TITLE
How to add repository directory

### ISSUE THREAD

**Issue by PoonamZ** [ellisdg/3DUnetCNN#100]
How to add the repository directory to the PYTHONPATH system variable.

**Comment by cloudlakecho** [comment]
Please, open Terminal in Linux, move to cloned 3DUnetCNN directory and type:
export PYTHONPATH=$PYTHONPATH:${PWD}

**Comment by cloudlakecho** [comment]
The steps are;
(1) Open Terminal
(2) Move to 3DUnetCNN directory ex) `$ cd /home/python/from internet/3DUnetCNN`
(3) Type `$ export PYTHONPATH=$PYTHONPATH:${PWD}`

To verify please type `$ echo $PYTHONPATH`, which will show like `$ /opt/ros/kinetic/lib/python2.7/dist-packages:/home/python/from internet/3DUnetCNN`
