### ISSUE TITLE
is conversion function necessary

### ISSUE THREAD

**Issue by connorchen** [ellisdg/3DUnetCNN#103]
hi @ellisdg 
you use conversion function to correct bias for some nifti data.
I wonder is conversion function necessary.  It cost a lot of time.
or without conversion function will make bad results?

**Comment by cloudlakecho** [comment]
If you mean "convert_brats_data("data/original", "data/preprocessed")" script, I believe the answer is yes. If you want to skip the script, you may dramatically change the train and file reading related Python file.

How about trying to use one folder from original and preprossed folder and how large amount of data set do you need to actually train the 3DUnetCNN?

**Comment by ellisdg** [comment]
I haven't tried training without doing the preprocessing. You could skip the preprocessing, and I wouldn't expect the results to be vastly different. But as far as time goes, training the network took me far more time than running the preprocessing. If you are able to train the network without doing the preprocessing, let me know what sort of results you get!

**Comment by connorchen** [comment]
thanks for your reply:
i don't give up preprocess yet, if i do i will tell you the result.

**Comment by cloudlakecho** [comment]
For the code test purpose, is possible train with only one folder of data set?
