### ISSUE TITLE
Doubt about get_multi_class_labels function

### ISSUE THREAD

**Issue by liuyongqing** [ellisdg/3DUnetCNN#104]
Hi @ellisdg, I have some double with 'get_multi_class_labels' function, it seems doesn't consider the background class with value '0', can you help me to understander it, Thank you very much!

`def get_multi_class_labels(data, n_labels, labels=None):

    new_shape = [data.shape[0], n_labels] + list(data.shape[2:])
    y = np.zeros(new_shape, np.int8)
    for label_index in range(n_labels):
        if labels is not None:
            y[:, label_index][data[:, 0] == labels[label_index]] = 1
        else:
            y[:, label_index][data[:, 0] == (label_index + 1)] = 1
    return y
`

**Comment by ellisdg** [comment]
In this code, I treat the background as being label-less. The UNet won't predict the presence of background, but instead will assign 0 to a given voxel if the prediction for none of the other labels exceeds the given threshold (default is 0.5).
