### ISSUE TITLE
Floating Point Exception & Length of Input Does Not Match Matrix Dimension

### ISSUE THREAD

**Issue by CloudChoSony** [ellisdg/3DUnetCNN#105]
While I run train.py, I am facing "Floating Point Exception (core dumped)" error. 
![image](https://user-images.githubusercontent.com/36999722/39274556-39c6c494-4897-11e8-8c5f-3777789da8f0.png)

While I run train_isensee2017.py file, I am encountering "Length of input (9) does not match matrix dimensions (2,2)" error.
![image](https://user-images.githubusercontent.com/36999722/39274692-a27eacd6-4897-11e8-9380-711c413cfa1d.png)

It looks like both case from Numpy or SimpleITK when they try to divided by zero. Anybody had the same issue before? 

My environment for reference, Anaconda, Python 2.7, Numpy 1.14, SimpleITK 1.1.

**Comment by CloudChoSony** [comment]
It was a mistake. I will figure out different way.

**Comment by shashikale** [comment]
Can you tell me how, since im having the same issue?your help is highly appreciated
