### ISSUE TITLE
Floating Point Exception & Length of Input Error during Sample Training

### ISSUE THREAD

**Issue by cloudlakecho** [ellisdg/3DUnetCNN#106]
While I run train.py, I am facing "Floating Point Exception (core dumped)" error. 
![image](https://user-images.githubusercontent.com/12093406/39275718-14c5ba16-489b-11e8-9a3d-94f84b7c7c8a.png)

While I run train_isensee2017.py file, I am encountering "Length of input (9) does not match matrix dimensions (2,2)" error.
![image](https://user-images.githubusercontent.com/12093406/39275704-079161ce-489b-11e8-8184-36546e316a85.png)

It looks like both case from Numpy or SimpleITK when they try to divided by zero. Anybody had the same issue before? 

My environment for reference, Anaconda, Python 2.7, Numpy 1.14, SimpleITK 1.1.

**Comment by weilan97** [comment]
@cloudlakecho I have the same problem.

**Comment by cloudlakecho** [comment]
@wilan97, do you have any progress?

**Comment by cloudlakecho** [comment]
@wilian97, my case was first data set regardless the name. 
Is the error came in the first data set in your case?

**Comment by cloudlakecho** [comment]
@weilan97, my case is always the first data set regardless the name.
Is the error came at the first data set in your data set?

**Comment by shashikale** [comment]
I have the same problem,

**Comment by cloudlakecho** [comment]
@shashikale I pause the trouble shooting.
One thing I observed that my case is always the first data set regardless the name. It looks like not depending on file name or file contents.

**Comment by shashikale** [comment]
Well, my goal is to understand this topology in details, so i started looking into pretrained model but with that also Im having issues with the pickel data, validation_ids.pkl not found. so im bit stuck.

**Comment by Soccergods** [comment]
If python3 is the requirement, maybe you can mention it in the requirements as well! Also there is an error in the spelling of PYTHONPATH in the README where it tells us to change the PYTHONPATH system var.

**Comment by necrodancer** [comment]
I suffered from same error.
I was using python2.7.
So I tried to change python version into 3.5.5. Then, the error disappeared.

**Comment by Thomas202** [comment]
Can you solve it now? I also encountered the same problem...

**Comment by cloudlakecho** [comment]
@Thomas202 I am sorry I still don't have time to install this tool in Python 3. My suggestion at this moment is using Python 3.5.5 (or any version 3) followed @necrodancer.
