### ISSUE TITLE
Training on BRATS2015 dataset

### ISSUE THREAD

**Issue by hailuoS** [ellisdg/3DUnetCNN#107]
I tried to use  BRATS2015 dataset for training, the ground truth label contains(0,1,2,3,4), so I changed the  
config["labels"] from (1,2,4) to (1,2,3,4) ,but after training, the evaluate result was wrong, the score of Enhancing Tumor was very low, almost all 0.  I  can't find where the problem is，should I change other parameters？ Could you help me about this problem? Thanks a lot

**Comment by ellisdg** [comment]
Are you using the basic UNet or the Isensee one with the improvements?

**Comment by ellisdg** [comment]
How many epochs did you train it for? What were the validation scores? What
was the training loss?

**Comment by hailuoS** [comment]
I only change the config["labels"], so the config["n_epochs"] is still 500. The training process stopped after 234 epochs due to the "early_stop". The final training loss was about -0.60 which was higher than the loss value(about -0.75) when I used brats2017 dataset.
The validation scores : WholeTumor(0.905559),TumorCore(0.736769) and the EnhancingTumor(0.00286). 
The score of EnhancingTumor seems wrong. I have checked the evaluate.py but didn't find the problem.
So I think the problem may appear during the training process.@ellisdg

**Comment by ellisdg** [comment]
It is surprising that you are getting such good scores for the whole tumor, but such bad scores for the enhancing tumor. Are you using the weighted dice coefficient?

Also, it might be helpful to look at the individual label prediction images. That is, you can take the input data from one (or more) of the validation cases, feed it into the model, and then save each of the output channels as it's own image. This will give you an idea what the predictions look like for the enhancing tumor label.

**Comment by hailuoS** [comment]
I changed the loss_function from the "weighted dice coefficient" to the "dice_coefficient"  to train the model.
The validation scores: WholeTumor(0.894838),TumorCore(0.702458) and the EnhancingTumor(0.687902)
This result looks normal，but I still can't understand why I got the wrong result when I used the "weighted dice coefficient" loss_function to train the model. @ellisdg

**Comment by gltmzq** [comment]
> Thanks for your help in advance.
> 
> I am trying to perform training using python traing_isensee2017.py after successful brats preprocessing.but I'm stuck at input mismatch.
> 
> home/shash/.local/lib/python2.7/site-packages/h5py/**init**.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
> from ._conv import register_converters as _register_converters
> Using TensorFlow backend.
> Reading: data/preprocessed/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/TCGA-12-0829/t1.nii.gz
> Reading: data/preprocessed/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/TCGA-12-0829/t1Gd.nii.gz
> Reading: data/preprocessed/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/TCGA-12-0829/flair.nii.gz
> Reading: data/preprocessed/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/TCGA-12-0829/t2.nii.gz
> Reading: data/preprocessed/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/TCGA-12-0829/truth.nii.gz
> Reading: data/preprocessed/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/TCGA-12-0829/t1.nii.gz
> 
> /tmp/SimpleITK-build/ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_svd.hxx: suspicious return value (2) from SVDC
> /tmp/SimpleITK-build/ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_svd.hxx: M is 2x2
> M = [ ...
> inf -nan
> -nan inf ]
> 
> Traceback (most recent call last):
> File "train_isensee2017.py", line 118, in 
> main(overwrite=config["overwrite"])
> File "train_isensee2017.py", line 71, in main
> subject_ids=subject_ids)
> File "/home/shash/Shashi/UnetTools/3DUnetCNN/unet3d/data.py", line 66, in write_data_to_file
> truth_dtype=truth_dtype, n_channels=n_channels, affine_storage=affine_storage, crop=crop)
> File "/home/shash/Shashi/UnetTools/3DUnetCNN/unet3d/data.py", line 26, in write_image_data_to_file
> images = reslice_image_set(set_of_files, image_shape, label_indices=len(set_of_files) - 1, crop=crop)
> File "/home/shash/Shashi/UnetTools/3DUnetCNN/unet3d/normalize.py", line 31, in reslice_image_set
> images = read_image_files(in_files, image_shape=image_shape, crop=crop_slices, label_indices=label_indices)
> File "/home/shash/Shashi/UnetTools/3DUnetCNN/unet3d/utils/utils.py", line 48, in read_image_files
> image_list.append(read_image(image_file, image_shape=image_shape, crop=crop, interpolation=interpolation))
> File "/home/shash/Shashi/UnetTools/3DUnetCNN/unet3d/utils/utils.py", line 60, in read_image
> return resize(image, new_shape=image_shape, interpolation=interpolation)
> File "/home/shash/Shashi/UnetTools/3DUnetCNN/unet3d/utils/utils.py", line 76, in resize
> interpolation=interpolation)
> File "/home/shash/Shashi/UnetTools/3DUnetCNN/unet3d/utils/sitk_utils.py", line 52, in resample_to_spacing
> default_value=default_value)
> File "/home/shash/Shashi/UnetTools/3DUnetCNN/unet3d/utils/sitk_utils.py", line 14, in sitk_resample_to_spacing
> origin=image.GetOrigin() + offset, default_value=default_value)
> File "/home/shash/Shashi/UnetTools/3DUnetCNN/unet3d/utils/sitk_utils.py", line 37, in sitk_new_blank_image
> image.SetDirection(direction)
> File "/home/shash/.local/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 3802, in SetDirection
> return _SimpleITK.Image_SetDirection(self, direction)
> RuntimeError: Exception thrown in SimpleITK Image_SetDirection: /tmp/SimpleITK/Code/Common/include/sitkTemplateFunctions.h:192:
> sitk::ERROR: Length of input (9) does not match matrix dimensions (2, 2).

I have the same problem, have you solved the problem? please help, thank you.

**Comment by biyoner** [comment]
Reading: data/preprocess/HGG/Brats17_TCIA_491_1/t1.nii.gz
Reading: data/preprocess/HGG/Brats17_TCIA_491_1/t1ce.nii.gz
Reading: data/preprocess/HGG/Brats17_TCIA_491_1/flair.nii.gz
Reading: data/preprocess/HGG/Brats17_TCIA_491_1/t2.nii.gz
/home/ilab/biyoner/tensorflow1.10/local/lib/python2.7/site-packages/nibabel/nifti1.py:582: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  ext_def = np.fromstring(ext_def, dtype=np.int32)
Reading: data/preprocess/HGG/Brats17_TCIA_491_1/truth.nii.gz
Reading: data/preprocess/HGG/Brats17_TCIA_491_1/t1.nii.gz
/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/utils/utils.py:74: RuntimeWarning: divide by zero encountered in divide
  new_spacing = np.divide(image.header.get_zooms(), zoom_level)
/tmp/SimpleITK-build/ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_svd.hxx: suspicious return value (2) from SVDC
/tmp/SimpleITK-build/ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo/vnl_svd.hxx: M is 2x2
M = [ ...
             inf             -nan 
            -nan              inf  ]
Traceback (most recent call last):
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/brats/train_isensee2017.py", line 117, in <module>
    main(overwrite=config["overwrite"])
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/brats/train_isensee2017.py", line 70, in main
    subject_ids=subject_ids)
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/data.py", line 66, in write_data_to_file
    truth_dtype=truth_dtype, n_channels=n_channels, affine_storage=affine_storage, crop=crop)
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/data.py", line 26, in write_image_data_to_file
    images = reslice_image_set(set_of_files, image_shape, label_indices=len(set_of_files) - 1, crop=crop)
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/normalize.py", line 31, in reslice_image_set
    images = read_image_files(in_files, image_shape=image_shape, crop=crop_slices, label_indices=label_indices)
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/utils/utils.py", line 48, in read_image_files
    image_list.append(read_image(image_file, image_shape=image_shape, crop=crop, interpolation=interpolation))
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/utils/utils.py", line 60, in read_image
    return resize(image, new_shape=image_shape, interpolation=interpolation)
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/utils/utils.py", line 76, in resize
    interpolation=interpolation)
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/utils/sitk_utils.py", line 52, in resample_to_spacing
    default_value=default_value)
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/utils/sitk_utils.py", line 14, in sitk_resample_to_spacing
    origin=image.GetOrigin() + offset, default_value=default_value)
  File "/home/ilab/biyoner/segmentation/brain/UnetCNN/unet3d/utils/sitk_utils.py", line 37, in sitk_new_blank_image
    image.SetDirection(direction)
  File "/home/ilab/biyoner/tensorflow1.10/local/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 3802, in SetDirection
    return _SimpleITK.Image_SetDirection(self, direction)
RuntimeError: Exception thrown in SimpleITK Image_SetDirection: /tmp/SimpleITK/Code/Common/include/sitkTemplateFunctions.h:192:
sitk::ERROR: Length of input (9) does not match matrix dimensions (2, 2).


I have the same problem, is there any possible solution?  Thanks. @gltmzq  @ellisdg @shashikale

**Comment by chengjianhong** [comment]
@biyoner you can retry it using python3.

**Comment by Thomas202** [comment]
Reader.SetFileNames(name)#load PNG
    Label = Reader.Execute()
    LabelArray=sitk.GetArrayFromImage(Label)
    LabelArray[:,:,1])).astype(np.uint8)/255
    Label=sitk.GetImageFromArray(LabelArray)
    Label.SetSpacing(Spacing)
    Label.SetOrigin(Origin)
    print(Direction)
    ''' Label.SetDirection(Direction)'''# this is erro
    Label.SetDirection((1,0,0,0,1,0,0,0,1))#lenght=9 

--------------------------------------
My original question was “sitk::ERROR: Length of input (9) does not match matrix dimensions (2, 2).”

But I solved it with the above code.。...

**Comment by anitchris** [comment]
> Reader.SetFileNames(name)#load PNG
> Label = Reader.Execute()
> LabelArray=sitk.GetArrayFromImage(Label)
> LabelArray[:,:,1])).astype(np.uint8)/255
> Label=sitk.GetImageFromArray(LabelArray)
> Label.SetSpacing(Spacing)
> Label.SetOrigin(Origin)
> print(Direction)
> ''' Label.SetDirection(Direction)'''# this is erro
> Label.SetDirection((1,0,0,0,1,0,0,0,1))#lenght=9
> 
> My original question was “sitk::ERROR: Length of input (9) does not match matrix dimensions (2, 2).”
> 
> But I solved it with the above code.。...

where did you make this changes?
