### ISSUE TITLE
How are the modalities Handled?

### ISSUE THREAD

**Issue by DaveLanday** [ellisdg/3DUnetCNN#109]
This wasn't immediately clear to me, but how are different modalities fed into the network? 
For example, a preprocessed brain scan is a folder containing the 4 different modality types. Each of these is an entire 3D image of the same brain. Are all of these considered separate inputs, ie. one is fed into the network after the other, or are the volumes combined so that each layer of the scan is a multi-channel image?

Thank you,
I think your work is really cool

**Comment by ellisdg** [comment]
Each modality is a separate channel going into the network. So with 4 modalities and the input shape to the network is (n, 4, x, y, z). Where n is the batch size, 4 is the modalities, x, y, and z are the image shapes. By comparison, a 2D network would take inputs of (n, 3, x, y) where 3 are the separate channels for red, green, and blue.

**Comment by DaveLanday** [comment]
Thank you for the reply and for your time. If I may ask a follow up question, does the nibabel package offer a quick and dirty way to merge 3D images to obtain multichannel volumes, Or do you use a tool like numpy to merge corresponding layers of each modality? Is this merge including in the generator you built to load batches into the model?  My group members and I took the latter approach for our own implementation. Thanks again!!

**Comment by ljljlj02** [comment]
If my image is a multi-channel image, how can I input it into the network and what should I do with it?
Any help would be greatly appreciated.
