### ISSUE TITLE
Deconvolution instead of Upsampling

### ISSUE THREAD

**Issue by alexklibisz** [ellisdg/3DUnetCNN#11]
This is another detail from the paper. In the [3d UNet prototxt definition](https://lmb.informatik.uni-freiburg.de/resources/opensource/3dUnet_miccai2016_no_BN.prototxt), they use "Deconvolution" layers which are different from Keras' `UpSampling3D`. The Keras library doesn't have 3D deconvolution anymore, but it's implemented in the [keras-contrib repository.](https://github.com/farizrahman4u/keras-contrib/blob/master/keras_contrib/layers/convolutional.py#L19)

**Comment by John1231983** [comment]
Hi, Could you tell me the Upsampling uses bilinear interpolation or not? In CAFFE, they have two options: bilinear or gaussian. Thanks
