### ISSUE TITLE
how do you convert mha to nii

### ISSUE THREAD

**Issue by connorchen** [ellisdg/3DUnetCNN#110]
hi,@ellisdg
        you use train data in nii format, but the brats2015 data in mha format, how do you convert mha to nii, can you share the source code.

**Comment by ellisdg** [comment]
[You can use SimpleITK for this](https://github.com/ellisdg/3DUnetCNN/commit/e6a8a482f15803b24fc4bda6e2a0bd001ca77c87#diff-75e48c7d6c92c0a359858478399bf94eR38)
