### ISSUE TITLE
model.summary() of this iseense2017 network?

### ISSUE THREAD

**Issue by nabsabraham** [ellisdg/3DUnetCNN#115]
is it possible to post your model.summary of this network? It doesn't seem obvious to me from the code but I'm still a beginner -  a summary would be really helpful!

**Comment by ellisdg** [comment]
Check out page 102 (i.e. page 107 in the PDF) of the [2017 BRATS proceedings](https://www.cbica.upenn.edu/sbia/Spyridon.Bakas/MICCAI_BraTS/MICCAI_BraTS_2017_proceedings_shortPapers.pdf) for a diagram describing the model structure. I tried to copy their model structure exactly.
