### ISSUE TITLE
About resizing and tensorflow-serving

### ISSUE THREAD

**Issue by diegoorellanaga** [ellisdg/3DUnetCNN#116]
Hello, I have trained your model with the default setting and with the BRATS dataset. I managed to upload it to tensorflow-serving. It only works when I call it with data with size `(?,1,128,128,128)` (old).  Because when I use a different size it complains. 

My question is the following: Is your model able to accept any 3d shape data? Or is it fixed to accept only the data which size is configured in the config variable? which in the (old) default case is `(?,1,128,128,128)`. (if I serve the model I don't have access to the config variable).

I'm asking you this because in the "Utils" folder you have resizing and normalization methods. And also because the errors tensorflow-serving throws are not related directly to a size mismatch. 

So I don't know if I have to dig in your code or in mine!  Thank you for your time!

**Comment by ellisdg** [comment]
What are the errors? Are they size mismatch errors? I run into size
mismatch errors when the input shapes are not divisible by 16. I can't
remember why this is off the top of my head, but it is related to the depth
of the unet being 4 with 4 max pooling operations (2^4 = 16).

**Comment by ellisdg** [comment]
If you don't want to resize the data, you could look into trying to change
the model so that the sizes won't be mismatched during concatenation. You
might be able to change the output of the max pooling operations or the
upsampling operations.

**Comment by diegoorellanaga** [comment]
Thank you for the suggestions.
