### ISSUE TITLE
Running prediction on CPU segmentation error

### ISSUE THREAD

**Issue by shashikale** [ellisdg/3DUnetCNN#121]
I'm trying to run prediction on Tenserflow with CPU.
python3.6 predict.py

I have modify the code to run on CPU

if __name__ == '__main__':
    os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
    with tf.device('/cpu'):
        main()

and I'm getting Segmentation fault (core dumped).
Any pointers?

**Comment by ellisdg** [comment]
I get segmentation faults with Tensorflow when there is not enough memory. Maybe that is your problem too?

**Comment by feichai2004** [comment]
I can run segmentation on CPU. My system memory is 16GB.
