### ISSUE TITLE
N4BiasfFieldCorrection

### ISSUE THREAD

**Issue by Goschjann** [ellisdg/3DUnetCNN#122]
Hi and first: thanks for the awesome script.

I would like to re-run it and using your manual I ran in the problem with the ants package (1.9.11), getting your warning 

"ANTs N4BIasFieldCorrection could not be found."
"Will try using SimpleITK for bias field correction"
" which will take much longer. To fix this problem, add N4BiasFieldCorrection" 
" to your PATH system variable. (example: EXPORT ${PATH}:/path/to/ants/bin)"

Then, simpleITK throws this error:

"RuntimeError: Exception thrown in SimpleITK N4BiasFieldCorrection: /tmp/SimpleITK/Code/Common/include/sitkMemberFunctionFactory.hxx:196:
sitk::ERROR: Pixel type: 16-bit signed integer is not supported in 3D byN3itk6simple32N4BiasFieldCorrectionImageFilterE"

I am running this thing on a EC2 instance and strangely nipype seems to not find ant though I added it to the path as described in section 4.3 of [this ant manual](https://howtoprogram.xyz/2016/10/14/install-apache-ant-ubuntu-16-04-lts-xenial-xerus/) as well as via `export ${PATH}:/usr/local/ant/bin`

I would be happy, if you could give me a hint on those questions:
* which version of ant did you run? 
* is there a special trick for adding ant to the path?
* do you know a workaround for the 16-bit int erorr with simpleITK? 

Thanks a lot in advance!

**Comment by ellisdg** [comment]
The warning statement was incorrect. It should be ```export PATH=${PATH}:/path/to/ants/bin``` or in your case ```export PATH=${PATH}:/usr/local/ant/bin``` if that is where you have your ANTs executables installed.

In the terminal you can test whether or not N4BiasFieldCorrection is located somewhere in your ```PATH``` system variable by running. ```which N4BiasFieldCorrection```. This will return nothing if the executable is not in your PATH and will return the path to the executable if it is located in your path.

**Comment by sneh-debug** [comment]
Demo_module is a folder which contain __init__.py file and code for preprocessing.

I  got segmentation error when tried on google colab.

import demo_module

demo_module.convert_brats_data("/content/drive/My Drive/brats/data/original", "/content/drive/My Drive/brats/data/preprocessed")
I got following errors:
RuntimeError: Command:
N4BiasFieldCorrection -d 3 --input-image /content/drive/My Drive/brats/data/original/HGG/BraTS19_CBICA_ABY_1/BraTS19_CBICA_ABY_1_t1.nii.gz --output /content/drive/My Drive/brats/data/preprocessed/HGG/BraTS19_CBICA_ABY_1/t1.nii.gz
Standard output:

Standard error:
 file Drive/brats/data/original/HGG/BraTS19_CBICA_ABY_1/BraTS19_CBICA_ABY_1_t1.nii.gz does not exist . 
Segmentation fault (core dumped)
Return code: 139
