### ISSUE TITLE
how to prepare the data

### ISSUE THREAD

**Issue by steeveen** [ellisdg/3DUnetCNN#126]
emmmm,hello  I just want to train it on my own dataset.
But I‘m confused on how to convert my data to the data your project needed.
Now I can just convert my data to a  ndarray（numpy）with the shape of （m,3,175,100,100).
The '3' means it contains two modalities and the label(ground truth or annotation)
According to my understanding,I should convert it to a h5 file and set the'data_file' with the path of it and then I can run the code. 
This is my try:
` with h5.File(op, 'w') as f:
            f.create_dataset('m1', data=np.expand_dims(patients[:,0, :, :, :], 1))
            f.create_dataset('m2', data=np.expand_dims(patients[:,1, :, :, :], 1))
            f.create_dataset('label', data=np.expand_dims(patients[:,2, :, :, :], 1))`

Obviously , it tell me there is no 'data' in it. Should I pack m1 and m2 together in a dataset named 'data'? I‘m not good at things about h5 file.
Can you help me with its structure or it will be better if you can show me the code converting from ndarray to h5 file

**Comment by melrobin** [comment]
I have run this code and there are three groups in the h5 file:
[melrobin@scorpion brats]$ python
Python 2.7.13 (default, Dec  1 2017, 09:21:53)
[GCC 6.4.1 20170727 (Red Hat 6.4.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> f=h5py.File('brats_data.h5','r')
>>> f.keys()
[u'affine', u'data', u'truth']

Maybe this can help.
