### ISSUE TITLE
Version of TF, Keras and Python

### ISSUE THREAD

**Issue by ChenFeiL** [ellisdg/3DUnetCNN#133]
Hi, could you please give me some suggestions about TF, Keras and Python versions?

**Comment by yuquant** [comment]
Didn't you see the requirements???

**Comment by yuquant** [comment]
愚蠢的问题，自己去看requiements

**Comment by zl535320706** [comment]
> 愚蠢的问题，自己去看requiements

Please comment after having a look at requirements.txt. And if you have no idea about the issue, you can keep silent.
