### ISSUE TITLE
process finished with exit code 139 (interrupted by signal 11 sigsegv)

### ISSUE THREAD

**Issue by ChenFeiL** [ellisdg/3DUnetCNN#136]
Hello,
I have followed the readme to train the brats data using the method of isensee2017. When performing python train_isensee2017.py, an error occurred after one epoch:

process finished with exit code 139 (interrupted by signal 11 sigsegv)

Could you please give me some ideas?

**Comment by necrodancer** [comment]
Same problem happened. 
I also performed python train_isensee2017.py.
I encountered this error as follows:
```
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:0a:00.0
totalMemory: 11.91GiB freeMemory: 10.92GiB
2018-09-12 13:40:53.940405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: TITAN Xp, pci bus id: 0000:0a:00.0, compute capability: 6.1)
Creating validation split...
Number of training steps:  133
Number of validation steps:  17
Epoch 1/500

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

**Comment by ChenFeiL** [comment]
> do you have solved this problem. I meet the same problem. But i do not know how to fix it.

It is the same error with Segmentation fault (core dumped) #58. I simply disabled the validation part.

**Comment by huazai-1994** [comment]
@Rainyfish @alkamid @necrodancer same problem happened!!Have anyone else fixed the problem? please give me some help,thanks!

**Comment by lpengc** [comment]
@ChenFeiL @necrodancer @Rainyfish @huazai-1994  try to set the "batch_size" and "validation_batch_size" in train.py as 1, it seems the number of data can't match the batch
