### ISSUE TITLE
Dice score loss on other 3d dataset

### ISSUE THREAD

**Issue by Pmac23** [ellisdg/3DUnetCNN#137]
The dice score reached to a maximum of 0.27 for running over 100 epochs and patch size 128,128,8 and n_ch=1 with 1000 patches generated from the dataset. Is there a solution to improve the dice score to generate better segmentation maps for the input?

**Comment by ellisdg** [comment]
When I'm getting poor dice scores, my go to for trying to figure out if something is going wrong is to try and visualize the outputs of the generators. You can write the outputs as nifti files like this:

```
def test_generators(train_generator, validation_generator):
    affine = np.diag(np.ones(4))
    for i in range(10):
        features, targets = next(train_generator)
        features_image = nib.Nifti1Image(features[0][0], affine)
        features_image.to_filename("{}_features.nii".format(i))
        targets_image = nib.Nifti1Image(targets[0][0], affine)
        targets_image.to_filename("{}_targets.nii".format(i))
        features, targets = next(validation_generator)
        features_image = nib.Nifti1Image(features[0][0], affine)
        features_image.to_filename("{}_features_validation.nii".format(i))
        targets_image = nib.Nifti1Image(targets[0][0], affine)
        targets_image.to_filename("{}_targets_validation.nii".format(i))
```

9 times out of 10, if I am getting poor scores, the training or validation data isn't getting output the way I was expecting it to. You can visualize the nifti images in something like Slicer3D, ITKSnap, or [Papaya](http://ric.uthscsa.edu/mango/papaya/index.html)(though I do often run into issues when using Papaya).
