### ISSUE TITLE
Link to Pre-Trained models is broken

### ISSUE THREAD

**Issue by GalDude33** [ellisdg/3DUnetCNN#138]
Can't download pre-trained models, the link seems to be broken or access is diabled.

![image](https://user-images.githubusercontent.com/18334824/43168020-61e3250e-8fa4-11e8-81dd-1983e11f6779.png)

**Comment by ellisdg** [comment]
Can you try again? I've updated the links, so they should work now.

**Comment by GalDude33** [comment]
Sorry, same problem again :no_mouth:

**Comment by ellisdg** [comment]
You get the exact same error message?

**Comment by GalDude33** [comment]
Yes.

**Comment by ellisdg** [comment]
The links on the [README](https://github.com/ellisdg/3DUnetCNN/blob/master/README.md) aren't pointing to the same location they were before. They are now pointing to Dropbox. So if you are getting the exact same error message, I don't see how you could be using the updated links unless OneDrive and Dropbox have the exact same error messages. Here are the links copied and pasted from the README:

## Pre-trained Models
The following Keras models were trained on the BRATS 2017 data:
* Isensee et al. 2017: 
[model](https://www.dropbox.com/s/tgr0chjbj5oz2f7/isensee_2017_model.h5?dl=1) ([weights only](https://www.dropbox.com/s/0hp9p1e8db92fq8/isensee_2017_weights.h5?dl=1))
* Original U-Net: 
[model](https://www.dropbox.com/s/m99rqxunx0kmzn7/tumor_segmentation_model.h5?dl=1) ([weights only](https://www.dropbox.com/s/p9g3j9zm9btp8n0/tumor_segmentation_weights.h5?dl=1))

Just to be clear. These links give you the exact same error message?

**Comment by GalDude33** [comment]
Now it is working! Thanks a lot.
