### ISSUE TITLE
how to recovery the Brats predication Image (155,240,240) from (128,128,128)

### ISSUE THREAD

**Issue by HUuxiaobin** [ellisdg/3DUnetCNN#142]
Hi, thanks for your nicely code. But it is actually very important to recovery the predication image shape (155,240,240) from (128,128,128) shape. Do you know how to do that, and I try many times to recovery it but it failed to be same as the initial ones.
Do you have some code to map the shape(128,128,128) to (155,240,240)?
Thank you in advance,
Best regards

**Comment by seanchain** [comment]
@HUuxiaobin Hi, same problem here, so have you found the method to do this now?

many thanks.

**Comment by HUuxiaobin** [comment]
@seanchain yes, i has already solved it, and we could have a discussion in wechat if you want.

**Comment by lokeshkvn** [comment]
@seanchain I have the same problem. Could you explain me too?

**Comment by swapb94** [comment]
@seanchain could be please share how you were able to regain the original dimensions ?

**Comment by nysuka** [comment]
this is how i did it. affine information is stored during the creation of hdf5 file in data.py after cropping and resizing and is retrieved in prediction.py. the original dimensions to the images can be restored using this affine with the corresponding resized images during construction of nifti from array (nib.Nifti1Image). for the predicted segmentation, i used nilearn's resample_to_img to convert to the original dimensions using the restored original.

**Comment by swapb94** [comment]
> this is how i did it. affine information is stored during the creation of hdf5 file in data.py after cropping and resizing and is retrieved in prediction.py. the original dimensions to the images can be restored using this affine with the corresponding resized images during construction of nifti from array (nib.Nifti1Image). for the predicted segmentation, i used nilearn's resample_to_img to convert to the original dimensions using the restored original.

I looked at some examples of resample_to_img, there they are passing a template as an argument. In this particular  case i tried replacing the template with the affine,
                                    resample_to_img(prediction_image,affine)
but it gives the following error,
TypeError: Data given cannot be loaded because it is not compatible with nibabel format:
1.6666666

Shape of affine : (4,4)
Shape of prediction_image : (3,144,144,144)

**Comment by HUuxiaobin** [comment]
manual crop the image and save the information, and modify the switch like following
2.crop is false and return image
 write_data_to_file(training_files, config["data_file"], image_shape=config["image_shape"],
       subject_ids=subject_ids,crop=False)

**Comment by nysuka** [comment]
@swapb94 the template is the image whose dimensions u want to resample to, not the affine.

**Comment by crazyzhaozhaojun** [comment]
> @seanchain yes, i has already solved it, and we could have a discussion in wechat if you want.
Ｈi,  can you explain to me? If can, my wechat is ZhaoJJJJun. Thanks.

**Comment by WrathofBhuvan11** [comment]
Guys how to change the shape of the Nifty1image format ?

**Comment by DecentMakeover** [comment]
@HUuxiaobin Hey, Would it be possible for you to share the code to get the predictions in original resolution? Thanks

**Comment by yan4821567** [comment]
I found this. It works.
https://github.com/ellisdg/3DUnetCNN/issues/114
