### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by swapb94** [ellisdg/3DUnetCNN#143]
Is there any way we can, we can visualize the predictions that have been generated, something similar to the gif that is present in the Readme. I do not expect the entire code, but if anyone could help me with atleast the mechanism, it would be very helpful.
Thank you in advance !

**Comment by athon2** [comment]
ITK-SNAP is a good visualization tool, or you can visualize it with matplotlib after loading the ".nii" format file with nibabel.

**Comment by swapb94** [comment]
By visualize, i meant the color distinction that can be seen in the gif in the readme. I trained the model, but mine predictions are in grayscale, whereas the ones in the readme show green, yellow color depending on the class of the tumor.

**Comment by huawenqing** [comment]
+1

**Comment by tsaiwentage** [comment]
+10086
