### ISSUE TITLE
problem of getting dataset

### ISSUE THREAD

**Issue by huazai-1994** [ellisdg/3DUnetCNN#145]
![qq 20180911202848](https://user-images.githubusercontent.com/33715651/45360396-0c753d80-b602-11e8-930c-c2906e408996.jpg)

The links above in the picture to load dataset has been out of use ,so is anyone else who cound offer a link to load the data?thank a lot

**Comment by forthtemple** [comment]
I'm having the same problem getting the data. Wish 3dunetCNN used training data that was publicly accessible

**Comment by Lililicg** [comment]
Hello, I can't download the dataset and the registration has not been passed. Could you please send your dataset to me? Thank you very much
