### ISSUE TITLE
Why do you choose shape(144,144,144)?

### ISSUE THREAD

**Issue by mjiansun** [ellisdg/3DUnetCNN#15]
Hi, ellisdg.
(1)I want to know why do you choose shape(144,144,144)?
(2)I guess your original data shape that is not (144,144,144), so I want to know how do you process your data?(crop or rescale?)

**Comment by ellisdg** [comment]
First, I [combine all of the non-zero pixel (foreground) locations from all of the images](https://github.com/ellisdg/3DUnetCNN/blob/master/normalize.py#L18). This image still has a large amount of blank space (background) in every direction. Then [I crop that image to the smallest image that still contains the foreground](https://github.com/ellisdg/3DUnetCNN/blob/master/normalize.py#L12) and [save the cropping values](https://github.com/ellisdg/3DUnetCNN/blob/master/normalize.py#L12).  Then for each of the input images, [I crop those images with the saved cropping values](https://github.com/ellisdg/3DUnetCNN/blob/master/data.py#L76). Then, the images are [resliced to match whatever the input shape was given](https://github.com/ellisdg/3DUnetCNN/blob/master/data.py#L77). (144, 144, 144) is just an arbitrary shape that served well for my purposes and didn't seem to significantly remove a lot of foreground data.

**Comment by mjiansun** [comment]
Thank you very much.
How many do you have data?
My data only have 60. So i want to know how do you extend data set?

**Comment by ellisdg** [comment]
1) This is what my data folder looks like:
![data_tree](https://cloud.githubusercontent.com/assets/8558995/26156497/2722c226-3adc-11e7-87c6-7c79c2d94868.png)

2) The BRATS data set has 274 sets of scans.
3) I have been curious about how someone could extend a radiological dataset. I don't know if flipping would help or hurt the training, but it would certainly be interesting to find out. I'm guessing it depends on the dataset. The authors of the [3D UNet paper](https://lmb.informatik.uni-freiburg.de/Publications/2016/CABR16/cicek16miccai.pdf) used only 3 images, but they used BSpline transformations to distort the data and thus extend their dataset.

**Comment by mjiansun** [comment]
That's good!

**Comment by mjiansun** [comment]
At [generator.py Line77](https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/generator.py#L77), i don't understand why `y[y > 0] = 1` can be training labels? I think [y](https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/generator.py#L75) shape is (batchsize, 1, x,y,z). So we should chage shape to (batchsize, nb_channels, x, y, z). But after this [process](https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/generator.py#L77), the shape has not changed.

**Comment by ellisdg** [comment]
@mjiansun I updated the code a week or so ago and now it can handle multi-class labels! The previous implementation could only handle a single class. that is why the size was (batchsize, 1, x, y, z).

**Comment by namco1992** [comment]
Hi @ellisdg ,
Based on your explanation, you first get a common foreground mask and then crop images with that mask. I guess the purpose of having a global foreground mask is that you wanna make sure all the cropped images have the same size, but you will have the same size images after the resize anyway, so what could be the consideration of having a prepared foreground mask?

Please right me if I am wrong about this, thanks.
