### ISSUE TITLE
Installation of ANTs N4BiasFieldCorrection and setting path 

### ISSUE THREAD

**Issue by Nareshchary** [ellisdg/3DUnetCNN#151]
# Install ANTs N4BiasFieldCorrection and add the location of the ANTs binaries to the PATH environmental variable :  
  i was downloaded Linux_Ubuntu14.04.tar.bz2 from the ANTs N4BiasFieldCorrection repository and extracted zip file.
 i am try to run ants.sh and antsBrainExtraction.sh i got error.
these commands i was tried
1) ./ants.sh
2) bash <path of .sh file>
3) sh <path of .sh file>

Is this correct procedure?
can anyone help me out how can i install  ANTs N4BiasFieldCorrection and add the location of the ANTs binaries to the PATH ?

**Comment by parvezamu** [comment]
First of all check your cmake version if it is less than 3.10.2 then Ants cannot be installed.....
Step First: cmake installation... you can search it .....installed with .tar.gz pacakage
step Second:  Follow this for installation ..................https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/
setep 3: open your bashrc and add this path 
#ANTs
export PATH=/usr/local/antsbin/bin:$PATH
export ANTSPATH=/usr/local/antsbin/bin/ 

source : http://miykael.github.io/nipype-beginner-s-guide/installation.html... install nipype with pip install nipype...then take the bias correction file inside cd $HOME/ants/bin in my case.....and run this file......for example python preprocess.py $HOME/path of your data.........you can also see this github: https://github.com/lelechen63/MRI-tumor-segmentation-Brats....for preprocessing .................

**Comment by akhanss** [comment]
Hi @Nareshchary 
Greetings. @parvezamu guidelines perhaps may work for you, however I have just followed the steps since I have no gui which is required by 'ccmake'
$ wget https://github.com/ANTsX/ANTs/releases/download/v2.1.0/Linux_Ubuntu14.04.tar.bz2
$ tar -xvjf Linux_Ubuntu14.04.tar.bz2
$ mv ANTs.2.1.0.Debian-Ubuntu_X64 bin
$ export PATH=/path/to/bin # path of previous step
Just as side notes, these are old binaries, however work for me for N4BiasFieldCorrection.
Hope this will help.
Best,
Azam.

**Comment by Ahgni** [comment]
> Hi @Nareshchary
> Greetings. @parvezamu guidelines perhaps may work for you, however I have just followed the steps since I have no gui which is required by 'ccmake'
> $ wget https://github.com/ANTsX/ANTs/releases/download/v2.1.0/Linux_Ubuntu14.04.tar.bz2
> $ tar -xvjf Linux_Ubuntu14.04.tar.bz2
> $ mv ANTs.2.1.0.Debian-Ubuntu_X64 bin
> $ export PATH=/path/to/bin # path of previous step
> Just as side notes, these are old binaries, however work for me for N4BiasFieldCorrection.
> Hope this will help.
> Best,
> Azam.

Hello, Azam,
I have a question, is that ANTs necessary for running the 3D U-Net?
My OS is Windows10, is that possible to run the 3D U-Net with or without ANTs?
Thank you

**Comment by jefflgaol** [comment]
> > Hi @Nareshchary
> > Greetings. @parvezamu guidelines perhaps may work for you, however I have just followed the steps since I have no gui which is required by 'ccmake'
> > $ wget https://github.com/ANTsX/ANTs/releases/download/v2.1.0/Linux_Ubuntu14.04.tar.bz2
> > $ tar -xvjf Linux_Ubuntu14.04.tar.bz2
> > $ mv ANTs.2.1.0.Debian-Ubuntu_X64 bin
> > $ export PATH=/path/to/bin # path of previous step
> > Just as side notes, these are old binaries, however work for me for N4BiasFieldCorrection.
> > Hope this will help.
> > Best,
> > Azam.
> 
> Hello, Azam,
> I have a question, is that ANTs necessary for running the 3D U-Net?
> My OS is Windows10, is that possible to run the 3D U-Net with or without ANTs?
> Thank you

According to https://github.com/arnab39/FewShot_GAN-Unet3D, it is optional.
