### ISSUE TITLE
What is the meaning of preprocess?

### ISSUE THREAD

**Issue by csuquan** [ellisdg/3DUnetCNN#152]
I cheak the code and find that the **preprocess** is just copying the original data?
why we need a preprocess procudure?
i dont konw~
please tell me ,tanks.

**Comment by nysuka** [comment]
In addition to file renaming for consistency, it also corrects for intensity bias in the MRI. please see https://github.com/ellisdg/3DUnetCNN/issues/90

**Comment by csuquan** [comment]
> In addition to file renaming for consistency, it also corrects for intensity bias in the MRI. please see #90

thanks!
