### ISSUE TITLE
Why the loss I get is negative?

### ISSUE THREAD

**Issue by muween** [ellisdg/3DUnetCNN#153]
![image](https://user-images.githubusercontent.com/28468626/46925725-fd016e00-d05f-11e8-8544-00adc2d7459f.png)

**Comment by nysuka** [comment]
@huawenqing the metric used here is the dice coefficient, a measure of similarity, ranges from 0 to 1. for the optimization to find the minimum, a negative is multiplied to it, so the more negative it is, the higher the similarity. please see https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/metrics.py

**Comment by huawenqing** [comment]
> @huawenqing the metric used here is the dice coefficient, a measure of similarity, ranges from 0 to 1. for the optimization to find the minimum, a negative is multiplied to it, so the more negative it is, the higher the similarity. please see https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/metrics.py

Now I get it ,Thank you for your detailed answer.
