### ISSUE TITLE
How to predict the new data ?

### ISSUE THREAD

**Issue by csuquan** [ellisdg/3DUnetCNN#154]
Runing the predict.py ,we could predict the 20% of rest test data.
but how can I use model to predict the new data?
please help me ~thanks

**Comment by nysuka** [comment]
@csuquan one way is to follow what is done for the 20% test data. 
first convert all the new data you want to test into .h5, could be individual cases or all into one. re-use https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/data.py
then feed the h5 of the new data into https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/prediction.py

if you don't have the truth, then will need to modify `def create_data_file` in data.py to contain just data and affine, and modify n_channels in `def write_data_to_file`

**Comment by zhoutonxgue** [comment]
@nysuka  I tried your method, but I'm not sure I just directly run the predict.py or I shoud change the train_isensee2017.py and other py files? Looking forward to your reply, thanks~

**Comment by akhanss** [comment]
Hi @nysuka 
I am just wondering if you can enlighten how to process individual image file during training/validation/testing. I just want to avoid preprocessing step beforehand rather process batch by batch in the runtime and keep it in memory. Thanks in advance.
Best,
Azam.

**Comment by WrathofBhuvan11** [comment]
Yeah can anyone explain how to do prediction or directly using models.
Please explain for both U Net and Isensee Model
