### ISSUE TITLE
resample_to_img(img, target_affine)

### ISSUE THREAD

**Issue by dmitrysarov** [ellisdg/3DUnetCNN#158]
https://github.com/ellisdg/3DUnetCNN/blob/323c9d607e646ed34db0f07d708a17be547121fa/unet3d/augment.py#L63
Is't it should be 

<pre>
data_list.append(resample_to_img(distort_image(image, flip_axis=flip_axis,
                                                       scale_factor=scale_factor), image.<b>affine</b>,
                                         interpolation="continuous").get_data())
</pre>

Same question at 68 line.

**Comment by nysuka** [comment]
@dmitrysarov according to https://www.pydoc.io/pypi/nilearn-0.4.0/autoapi/image/resampling/index.html#image.resampling.resample_to_img, the second parameter to resample_to_img is the target image, not affine.

**Comment by dmitrysarov** [comment]
thanx! mixed up with
http://nilearn.github.io/modules/generated/nilearn.image.resample_img.html
