### ISSUE TITLE
Structure.?

### ISSUE THREAD

**Issue by 32nguyen** [ellisdg/3DUnetCNN#16]
Hi,
Thank you so much for the post. 
I would like to ask you that: Will this 3D CNN work well with some the volume has complicated structure (such as retina, or tree branches)

**Comment by ellisdg** [comment]
I assume so, but I've never used it for those applications, so I don't really know. The authors of the [3D UNet paper](https://lmb.informatik.uni-freiburg.de/Publications/2016/CABR16/cicek16miccai.pdf) used it to segment neurons, which, from my understanding, have quite complicated structure.

**Comment by 32nguyen** [comment]
Thanks, 
I am interested in to see if 3D works well on my case. I am still explore the data flowing in your architecture. But I am still waiting the permission to download the data. I have not grant it yet. 
By the wait, may I ask the function correct_bias(input_file, output_file).  What are the input_file and output_file's format? Are they a intensity numpy volume? It is a little hard for me to keep track without the data.
Bests,

**Comment by 32nguyen** [comment]
I think I got it. they are just the name file like .nii. 
but I got Interface N4BiasFieldCorrection failed to run

**Comment by 32nguyen** [comment]
I fixed my dumb mistake by reinstalling nipype and ANTs.
Thanks
