### ISSUE TITLE
Install ANTs N4BiasFieldCorrection and add the location of the ANTs binaries to the PATH environmental variable

### ISSUE THREAD

**Issue by angechen** [ellisdg/3DUnetCNN#160]
Is this going to happen in ubunturi? What are the steps？

**Comment by akhanss** [comment]
Hi @angechen 
Greetings. I have just follow the steps
$ wget https://github.com/ANTsX/ANTs/releases/download/v2.1.0/Linux_Ubuntu14.04.tar.bz2
$ tar -xvjf Linux_Ubuntu14.04.tar.bz2
$ mv ANTs.2.1.0.Debian-Ubuntu_X64 bin
$ export PATH=/path/to/bin # path of previous step
Just as side notes, these are old binaries, however work for me for N4BiasFieldCorrection.
Hope this will help.
Best,
Azam.

**Comment by cagcag** [comment]
Thanks a lot.I will try it .Thanks again.
