### ISSUE TITLE
How to solve the Segmentation fault (core dumped).

### ISSUE THREAD

**Issue by csudage** [ellisdg/3DUnetCNN#161]
Thanks, Mr. Zhang. I am glad that you have solved the segmentation fault. However, after deleted "validation_data=validation_generator", the " tumor_segmentation_model.h5" file cannot be generated.How do you deal with this question,looking forward to your reply. Thank you in advance.

_Originally posted by @DongqingZhang in https://github.com/ellisdg/3DUnetCNN/issues/58#issuecomment-347932756_

**Comment by csudage** [comment]
i use "conda install pytables",because there are not pytables in my computer,so i can't use HDF5.

**Comment by zhoutonxgue** [comment]
@csudage  Did you solve it? I also has the problem 'Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)' , I tried every solutions in the issues, not work, and it only runs when I delete the "validation_data=validation_generator" but I can't got val_loss, does anyone has better solutions, thanks in advance.

**Comment by csudage** [comment]
@zhoutonxgue you can use "conda install pytables" to solve it,if you use the conda.

**Comment by zhoutonxgue** [comment]
thanks, I solved by setting workers=0

**Comment by zhoutonxgue** [comment]
@csudage  thanks, I solved by setting workes=0
