### ISSUE TITLE
preprocessing

### ISSUE THREAD

**Issue by cagcag** [ellisdg/3DUnetCNN#165]
>>> from preprocess import convert_brats_data
Using TensorFlow backend.
/home/cag/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py:766: DeprecationWarning: builtin type EagerTensor has no __module__ attribute
  EagerTensor = c_api.TFE_Py_InitEagerTensor(_EagerTensorBase)
/home/cag/.local/lib/python3.5/site-packages/tensorflow/python/util/tf_inspect.py:45: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if d.decorator_argspec is not None), _inspect.getargspec(target))
/home/cag/.local/lib/python3.5/site-packages/tensorflow/python/keras/_impl/keras/backend.py:4046: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/cag/.keras/keras.json' mode='r' encoding='UTF-8'>
  _config = json.load(open(_config_path))
>>> convert_brats_data("data/original", "data/preprocessed")
>>> 

Is there any question in this step?The program doesn't seem to  run。

**Comment by akhanss** [comment]
Hi @cagcag 
Greetings. Warning message before "convert_brats_data("data/original", "data/preprocessed")" lines generated from tensorflow. In my case, other subsequent steps should be worked! 
Just make sure that you have placed all the data at ./data/original directory.
Hope this help.
Best,
Azam.

**Comment by cagcag** [comment]
Thank you very much.I will try again.
