### ISSUE TITLE
How ro train with 2D slice data?

### ISSUE THREAD

**Issue by YourGc** [ellisdg/3DUnetCNN#168]
Hi
Thanks a lot for opening source code.
My dataset's shape is 2D * high with the PNG format, while 'high' is the third dimension， how can i process the data to use the model ?

**Comment by akhanss** [comment]
If 'high is the third dimension, then 2D * high is ultimately 3D data. This repo is fit for such data. Hope this will help. Thank you.

Best,
Azam.
