### ISSUE TITLE
      Add the repository directory to the PYTONPATH system variable

### ISSUE THREAD

**Issue by cagcag** [ellisdg/3DUnetCNN#169]
What's the detailed steps of :
Add the repository directory to the PYTONPATH system variable:

$ export PYTHONPATH=${PWD}:$PYTHONPATH

**Comment by akhanss** [comment]
I think you should use 'pwd' instead of 'PWD'. pwd should indicate the cloned directory. Thank you.
$ export PYTHONPATH=${pwd}:$PYTHONPATH
Best,
- Azam.

**Comment by parvezamu** [comment]
![capture](https://user-images.githubusercontent.com/23691260/50389671-ef571b80-0767-11e9-94f7-4e9f0e6bf301.JPG)
