### ISSUE TITLE
How to restore the segmentation image to the original image shape?

### ISSUE THREAD

**Issue by chengjianhong** [ellisdg/3DUnetCNN#172]
Hi,
I had trained the model with` config["image_shape"] = (128, 128, 128)` and  `config["patch_shape"] = None`, so that the shape of all the inference volumes is equal to `128 x 128 x 128`. However, there is a problem that the shape of my segmentation volumes can't be the same shape as the BraTS provided if I want to particate the Challenge. So how to resolve it or give me some advice.
Best wishes,
Jianhong Cheng

**Comment by akhanss** [comment]
Hi @chengjianhong 
I am just wondering if you can check #159 
Specifically, the response (https://github.com/ellisdg/3DUnetCNN/issues/159#issuecomment-438330573) can solve your issue.
Thank you.
Best, 
Azam.
