### ISSUE TITLE
RuntimeWarning&ImportWarning on preprocessing

### ISSUE THREAD

**Issue by VRER1997** [ellisdg/3DUnetCNN#176]
Hi,
While i am running the preprocessing, "from preprocess import convert_brats_data" command is executing occuring some warnings.
Your help is highly appreciated!!

(graduate) bash-3.2$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 14:01:38)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from preprocess import convert_brats_data
Using TensorFlow backend.
/Users/c1over/anaconda3/envs/graduate/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed,may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/Users/c1over/anaconda3/envs/graduate/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from__spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/Users/c1over/anaconda3/envs/graduate/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/Users/c1over/anaconda3/envs/graduate/lib/python3.6/site-packages/tensorflow/python/keras/backend.py:4900: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/c1over/.keras/keras.json' mode='r' encoding='UTF-8'>
  _config = json.load(open(_config_path))
/Users/c1over/anaconda3/envs/graduate/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed,may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/Users/c1over/anaconda3/envs/graduate/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from__spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/Users/c1over/anaconda3/envs/graduate/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed,may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/Users/c1over/anaconda3/envs/graduate/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from__spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
>>> convert_brats_data("data/original", "data/preprocessed")

**Comment by Lynnljx** [comment]
I have the same question
