### ISSUE TITLE
ImportError: cannot import name 'InstanceNormalization'

### ISSUE THREAD

**Issue by b-z** [ellisdg/3DUnetCNN#182]
> Traceback (most recent call last):
>   File "/home/zhoubw16/3DUnetCNN/unet3d/model/unet.py", line 103, in create_convolution_block
>     from keras_contrib.layers.normalization import InstanceNormalization
> **ImportError: cannot import name 'InstanceNormalization'**
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "train_isensee2017.py", line 117, in <module>
>     main(overwrite=config["overwrite"])
>   File "train_isensee2017.py", line 79, in main
>     n_base_filters=config["n_base_filters"])
>   File "/home/zhoubw16/3DUnetCNN/unet3d/model/isensee2017.py", line 47, in isensee2017_model
>     in_conv = create_convolution_block(current_layer, n_level_filters)
>   File "/home/zhoubw16/3DUnetCNN/unet3d/model/unet.py", line 105, in create_convolution_block
>     raise ImportError("Install keras_contrib in order to use instance normalization."
> **ImportError: Install keras_contrib in order to use instance normalization.**
> **Try: pip install git+https://www.github.com/farizrahman4u/keras-contrib.git**

I have tried to install keras_contrib through pip, but the problem still occurred.

Is that a problem of **keras_contrib**? https://github.com/keras-team/keras-contrib/issues/466

**Comment by b-z** [comment]
According to the author of keras_contrib, 
the code should be modified to
```
from keras_contrib.layers.normalization.instancenormalization import InstanceNormalization
```

**Comment by IamShubhamGupto** [comment]
> According to the author of keras_contrib,
> the code should be modified to
> 
> ```
> from keras_contrib.layers.normalization.instancenormalization import InstanceNormalization
> ```

Where exactly is this modification ?

**Comment by akhanss** [comment]
@IamShubhamGupto 
File: unet3d/model/unet.py
Line # 102
Please replace "from keras_contrib.layers.normalization import InstanceNormalization"
with "from keras_contrib.layers.normalization.instancenormalization import InstanceNormalization"

Hope this will solve your issue.

Best,
Azam

**Comment by sneh-debug** [comment]
@b-z when i tried same in google colab i got same error
ImportError: cannot import name 'InstanceNormalization'
