### ISSUE TITLE
Place the unzipped folders in the brats/data/original

### ISSUE THREAD

**Issue by andygreg** [ellisdg/3DUnetCNN#188]
"Place the unzipped folders in the brats/data/original"
I don't understand this part, I cannot find a directory in brats called data? Do I have to create it myself?

**Comment by b-z** [comment]
yes, create it yourself

**Comment by andygreg** [comment]
thank you !

**Comment by chenxiaodanhit** [comment]
May I ask you the type of data? I want to use my own data to train. Thank you!
