### ISSUE TITLE
permute=True?

### ISSUE THREAD

**Issue by angechen** [ellisdg/3DUnetCNN#190]
if permute =True,will the data be augmented?  I see that permute has 48 possibilities,will the number of data be 48 times what it was before if permute =True？

**Comment by ellisdg** [comment]
When permute is set to true, the image being input to the model for
training will be randomly permuted in one of the 48 possible permutations
of that image. This random selection is done each time that image is fed to
the model for training. It does not feed all 48 permutations to the model
during the same epoch. So, the amount of data being fed to the model for
training per epoch remains the same.

**Comment by angechen** [comment]
Thanks a lot for your detailed instructions.
