### ISSUE TITLE
About train in my own ct data 

### ISSUE THREAD

**Issue by Endless-Hao** [ellisdg/3DUnetCNN#199]
@ellisdg  hello! I want to train in my own data. My data just have one modality(CT) and my label also has just one label. Should i change the code about input_shape from (4,128,128,128) to (1,128,128,128)  in isensee2017_model() ?

**Comment by DecentMakeover** [comment]
hey did you fix this ?

**Comment by Endless-Hao** [comment]
@DecentMakeover  NO

**Comment by chenxiaodanhit** [comment]
Hello，Did you sucess to train your own data?

**Comment by Endless-Hao** [comment]
@chenxiaodanhit  Yes, but I use another sample 3dunet, not this.

**Comment by chenxiaodanhit** [comment]
Could you share the link to me? thank you very much

**Comment by Endless-Hao** [comment]
@chenxiaodanhit  tomorrow i send you

**Comment by chenxiaodanhit** [comment]
@Endless-Hao Thank you very much!

**Comment by Endless-Hao** [comment]
@give me you email，i send code. I change some let it work.

**Comment by chenxiaodanhit** [comment]
1615443838@qq.com Thank you!

**Comment by DecentMakeover** [comment]
Hmmm, hey when you say another sample unet, did you just replace the model in place of the iseene model ?

**Comment by nwzhr** [comment]
Hi, could you please share the link to me either? Thanks a lot. Here's my email: d991007@outlook.com

**Comment by Endless-Hao** [comment]
@nwzhr  OK i will send you

**Comment by AlanAlfredHe** [comment]
> @nwzhr OK i will send you

Could you also send me the code? I am also working on CT image with one label. Thanks a lot!
E-mail: 116010063@link.cuhk.edu.cn

**Comment by MyLoveBin** [comment]
Hi, could you please share the link to me either?  Here's my email:1025512957@qq.com.Thanks a lot.

**Comment by fatemeh-ghofrani** [comment]
@Endless-Hao  Could you please share the link to me either?
Here's my email:fatemeh.ghofrani93@gmail.com.
Really apreatiate you.

**Comment by wuzihaoo** [comment]
> @ellisdg hello! I want to train in my own data. My data just have one modality(CT) and my label also has just one label. Should i change the code about input_shape from (4,128,128,128) to (1,128,128,128) in isensee2017_model() ?

Hi could you please send me a copy either? Thanks!
E-mail: zihaowu_1995@hotmail.com

**Comment by nysuka** [comment]
to train 1 modality and 1 segmentation label, just need to change in train_isensee2017.py
`config["labels"] = (1, )`
`config["all_modalities"] = ["name of ct file"]`

no need to change isensee2017_model

**Comment by Keepbright** [comment]
Hi, @Endless-Hao ,Could you tell me which 3dunet example you used?
If you can, could you share me the code either?
Thanks!
E-mail: fengruolan@outlook.com

**Comment by mit10000** [comment]
@Endless-Hao 
Please share your resource with me,
hubicheng99@gmail.com

Thanks.

**Comment by birdflyto** [comment]
> @ellisdg hello! I want to train in my own data. My data just have one modality(CT) and my label also has just one label. Should i change the code about input_shape from (4,128,128,128) to (1,128,128,128) in isensee2017_model() ?

could you share the sample with me, 
1521361730@qq.com
Thanks

**Comment by MyLoveBin** [comment]
你可以加我qq1025512957,详细聊------------------ 原始邮件 ------------------
发件人: "birdflyto"<notifications@github.com>
发送时间: 2019年11月19日(星期二) 下午4:04
收件人: "ellisdg/3DUnetCNN"<3DUnetCNN@noreply.github.com>;
抄送: "MyLoveBin"<1025512957@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ellisdg/3DUnetCNN] About train in my own ct data  (#199)


 
@ellisdg hello! I want to train in my own data. My data just have one modality(CT) and my label also has just one label. Should i change the code about input_shape from (4,128,128,128) to (1,128,128,128) in isensee2017_model() ?
  
could you share the sample with me,
 1521361730@qq.com
 Thanks
 
&mdash;

**Comment by FengZhiheng** [comment]
> @chenxiaodanhit Yes, but I use another sample 3dunet, not this.

It's very kind of you to share your 3D model. This is my E-mail address(zhihengfeng5371@163.com), thank you very much.

**Comment by nightandweather** [comment]
> @chenxiaodanhit Yes, but I use another sample 3dunet, not this.

could you share the sample with me..?

i'm interested in tumor segmentation in ct

thank you very much
dlrkdgns1324@gmail.com < this is my email address

**Comment by wjj001-dl** [comment]
> @ellisdg hello! I want to train in my own data. My data just have one modality(CT) and my label also has just one label. Should i change the code about input_shape from (4,128,128,128) to (1,128,128,128) in isensee2017_model() ?

Could you share the link to me? thank you very much。This is my E-mail address(junjunwang_1@163.com)

**Comment by merediiii** [comment]
Could you please share the link to me? Thanks a lot.
This is my e-mail(realmadridivy@126.com)

**Comment by chenjingyi-star** [comment]
@Endless-Hao Could you please share the link to me either?
Here's my email:2953288282@qq.com
Really apreatiate you.

**Comment by Endless-Hao** [comment]
@chenjingyi-star  you can download the code in my github. I uploaded them. Here：https://github.com/Endless-Hao/3D-Unet-for-Medical-image
