### ISSUE TITLE
Suggestions to train new data

### ISSUE THREAD

**Issue by DecentMakeover** [ellisdg/3DUnetCNN#200]
Hi

Thanks for sharing your work.
I have a dataset which just consists of just a 3d image which is in nii.gz form and a segmentation which is also in nii.gz form

Because the brats dataset has many modalities i am not sure how to use this for my case,

Could you kindly suggest what changes i could make to run this network on my data.

Thanks in advance.

**Comment by divinediu** [comment]
Hi my data is similar too. I am having the same issue. I changed modalities but the renaming didn't work.
