### ISSUE TITLE
configuration of your pre-trained model 

### ISSUE THREAD

**Issue by luciaL** [ellisdg/3DUnetCNN#203]
Hello, I want to use your pre-trained weight to initialize the parameters of the network to train my dataset.  But I got a error shows the weight file containing 60 layers while the model containing 30 layers. Could you share the configuration of your weight file?

**Comment by abheesht17** [comment]
I got the same issue.
"ValueError: You are trying to load a weight file containing 60 layers into a model with 57 layers."

**Comment by abheesht17** [comment]
I think we can load the weights using the following command (just a suggestion):
model.load_weights("put your path here", by_name=True)
