### ISSUE TITLE
prediction on the whole image

### ISSUE THREAD

**Issue by DecentMakeover** [ellisdg/3DUnetCNN#205]
Has anyone been successful to get predictions on the whole image? i mean to get prediction output as the original resolution not as the output image being (128,128,128)

**Comment by parvezamu** [comment]
I am not sure but may be this code helps you

import nibabel as nib
from nilearn.image import resample_to_img
import numpy as np
p=nib.load("F:\\13Aug\\batchsize1\\fold6\\brats\\prediction\\TCGA-02-245\\prediction.nii.gz")
q=nib.load("F:\\data\\Pre-operative_TCGA_GBM_NIfTI_and_Segmentations\\TCGA-02-245\\t1ce.nii.gz")
r=resample_to_img(p, q, interpolation='nearest')
r1=r.get_affine()
r2=r.get_data()
r3=nib.Nifti1Image(r2, r1)
r3.to_filename("F:\\Results\\training_results\\BraTS19_TCIA06_409_1\\BraTS19_TCIA06_409_1.nii.gz")
