### ISSUE TITLE
About writing a h5 file on BraTS validation dataset 

### ISSUE THREAD

**Issue by chengjianhong** [ellisdg/3DUnetCNN#210]
@ellisdg Hi, I think there is a insufficiency on writing  a h5 file for BraTS validation dataset(without ground truth) in code. Because it needs a ground truth data together with four modalities data. I make it by copying a ground turth data into every subject path, which is unadvisable. So I think It needs to  update the method to generate h5 files for the validation set or testing set.

**Comment by nysuka** [comment]
to generate h5 files without truth data for testing, you need to write out the h5 files without the truth storage, so in `data.py`, you can modify `def create_data_file` to skip the truth_storage with a flag or a separate function name and call it in `write_data_to_file`. during prediction, in `prediction.py`, modify `run_validation_case` by deleting all processing of truth data.
