### ISSUE TITLE
TypeError: environment can only contain strings

### ISSUE THREAD

**Issue by acumino** [ellisdg/3DUnetCNN#219]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 163, in convert_brats_data
    no_bias_correction_modalities=no_bias_correction_modalities)
  File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 131, in convert_brats_folder
    normalize_image(image_file, out_file, bias_correction=perform_bias_correction)
  File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 112, in normalize_image
    correct_bias(in_file, out_file)
  File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 69, in correct_bias
    done = correct.run()
  File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 335, in run
    self._check_version_requirements(self.inputs)
  File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 258, in _check_version_requirements
    if names and self.version:
  File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\ants\base.py", line 125, in version
    return Info.version()
  File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 1063, in version
    terminal_output='allatonce').run()
  File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 376, in run
    runtime = self._run_interface(runtime)
  File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 758, in _run_interface
    runtime = run_command(runtime, output=self.terminal_output)
  File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\utils\subprocess.py", line 115, in run_command
    close_fds=(not sys.platform.startswith('win')),
  File "C:\Users\Acuminous\Anaconda3\lib\subprocess.py", line 777, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Acuminous\Anaconda3\lib\subprocess.py", line 1180, in _execute_child
    startupinfo)
TypeError: environment can only contain strings

**Comment by a1029602653** [comment]
I also have this error

**Comment by wjj001-dl** [comment]
have you solved this problem?

> Traceback (most recent call last):
> File "", line 1, in
> File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 163, in convert_brats_data
> no_bias_correction_modalities=no_bias_correction_modalities)
> File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 131, in convert_brats_folder
> normalize_image(image_file, out_file, bias_correction=perform_bias_correction)
> File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 112, in normalize_image
> correct_bias(in_file, out_file)
> File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 69, in correct_bias
> done = correct.run()
> File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 335, in run
> self._check_version_requirements(self.inputs)
> File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 258, in _check_version_requirements
> if names and self.version:
> File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\ants\base.py", line 125, in version
> return Info.version()
> File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 1063, in version
> terminal_output='allatonce').run()
> File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 376, in run
> runtime = self._run_interface(runtime)
> File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 758, in _run_interface
> runtime = run_command(runtime, output=self.terminal_output)
> File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\utils\subprocess.py", line 115, in run_command
> close_fds=(not sys.platform.startswith('win')),
> File "C:\Users\Acuminous\Anaconda3\lib\subprocess.py", line 777, in **init**
> restore_signals, start_new_session)
> File "C:\Users\Acuminous\Anaconda3\lib\subprocess.py", line 1180, in _execute_child
> startupinfo)
> TypeError: environment can only contain strings

have you solved this problem?

**Comment by acumino** [comment]
> have you solved this problem?
> 
> > Traceback (most recent call last):
> > File "", line 1, in
> > File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 163, in convert_brats_data
> > no_bias_correction_modalities=no_bias_correction_modalities)
> > File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 131, in convert_brats_folder
> > normalize_image(image_file, out_file, bias_correction=perform_bias_correction)
> > File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 112, in normalize_image
> > correct_bias(in_file, out_file)
> > File "C:\Users\Acuminous\Desktop\3DUnetCNN-master\brats\preprocess.py", line 69, in correct_bias
> > done = correct.run()
> > File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 335, in run
> > self._check_version_requirements(self.inputs)
> > File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 258, in _check_version_requirements
> > if names and self.version:
> > File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\ants\base.py", line 125, in version
> > return Info.version()
> > File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 1063, in version
> > terminal_output='allatonce').run()
> > File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 376, in run
> > runtime = self._run_interface(runtime)
> > File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\interfaces\base\core.py", line 758, in _run_interface
> > runtime = run_command(runtime, output=self.terminal_output)
> > File "C:\Users\Acuminous\Anaconda3\lib\site-packages\nipype\utils\subprocess.py", line 115, in run_command
> > close_fds=(not sys.platform.startswith('win')),
> > File "C:\Users\Acuminous\Anaconda3\lib\subprocess.py", line 777, in **init**
> > restore_signals, start_new_session)
> > File "C:\Users\Acuminous\Anaconda3\lib\subprocess.py", line 1180, in _execute_child
> > startupinfo)
> > TypeError: environment can only contain strings
> 
> have you solved this problem?

No I did this project on Linux. There it worked fine.
