### ISSUE TITLE
unused list:stds unet3d/normalize.py

### ISSUE THREAD

**Issue by rasaxena** [ellisdg/3DUnetCNN#22]
Hi ellisdg!

Instead of taking mean of the standard dev, standard dev of the 'means' were taken. not sure if this was the intention as 'stds' is unused. (find below)

def normalize_data_storage(data_storage):
--
  | means = list()
  | stds = list()
  | for index in range(data_storage.shape[0]):
  | data = data_storage[index]
  | means.append(data.mean(axis=(1, 2, 3)))
  | stds.append(data.std(axis=(1, 2, 3)))
  | mean = np.asarray(means).mean(axis=0)
  | **std = np.asarray(means).std(axis=0)**
  | for index in range(data_storage.shape[0]):
  | data_storage[index] = normalize_data(data_storage[index], mean, std)
  | return data_storage

**Comment by ellisdg** [comment]
Thanks for pointing this out!
