### ISSUE TITLE
brats.train not found

### ISSUE THREAD

**Issue by davidweioct** [ellisdg/3DUnetCNN#221]
Hello,
I tried to run the preprocess, but it seems not working because the "brats" module was not found in "from brats.train import config". Is the "brats" file included in the folder? I'm new to this project and start from the old data referring to "(You can also get the older versions of the dataset without signing up: LGG GBM)". How should I do the preprocess?

Thank you so much!

**Comment by nysuka** [comment]
brats is the folder and the file is train.py, which contains config. this is standard python import syntax.

**Comment by davidweioct** [comment]
Thank you! It seems the __init__.py files were accidentally removed for some reason. Now it works good.
