### ISSUE TITLE
question about the difference between isensee2017 and the paper

### ISSUE THREAD

**Issue by Shawn0099** [ellisdg/3DUnetCNN#222]
Hi,thanks for your sharing.
I read the paper you mentioned which described the Isensee model,and I found some differences.It seems that the author of the paper uses a 2D network,which is quite different form your architecture,because as described in the isensee2017.png,your network uses 3D full images.Can you tell me your what you think?it would be wery helpful.
Thanks a lot.

**Comment by nysuka** [comment]
Isensee 2017 Brats paper uses 3D.
