### ISSUE TITLE
visualize prediction results

### ISSUE THREAD

**Issue by mit10000** [ellisdg/3DUnetCNN#223]
Thanks ellisdg for sharing.
Given a MRI, after do prediction, how to map back the prediction to the original image, and visualize the difference between prediction and truth? This is a basic function of any ML project, can anyone help on this? Thanks.

**Comment by pervinh** [comment]
Hi,
Did you manage to solve this, i am interested too?

**Comment by sneh-debug** [comment]
@mit10000 what dice score you get for validation cases? and for how much epochs?

**Comment by ellisdg** [comment]
@sneh-debug I updated the README with the dice scores for the BraTS 2020 challenge for this model. I also updated the ```predict.py``` script in the ```brats``` folder to resample the predicted images back into the original spacing. Now that they are in the original spacing, you can visualize them in an image viewer such as [Papaya viewer](http://rii.uthscsa.edu/mango/papaya/) or [3DSlicer](https://www.slicer.org/).

Feel free to open this issue back up if you have more questions on visualizing the results.
