### ISSUE TITLE
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'

### ISSUE THREAD

**Issue by Brandedahall** [ellisdg/3DUnetCNN#225]
Hi there.

I've been trying to run the prediction on a model which I had just trained, but I've run into the issue pasted below.

I'm using plaidml as the backend due to  Theano **refusing** to work at all on my system and this was the best workaround. I repeat, I **CANNOT** use the default backends.

I would be most appreciative if you could help me move past this error!
```
(3DUnetCNN) C:\Users\user\Desktop\3DUnetCNN-master\brats>python predict.py
C:\Users\user\Anaconda3\envs\3DUnetCNN\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be i
nstalled with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Using plaidml.keras.backend backend.
Loading pre-trained model
INFO:plaidml:Opening device "opencl_nvidia_geforce_gtx_1660.0"
Traceback (most recent call last):
  File "predict.py", line 19, in <module>
    main()
  File "predict.py", line 15, in main
    output_dir=prediction_dir)
  File "C:\Users\user\Desktop\3DUnetCNN-master\unet3d\prediction.py", line 155, in run_validation_cases
    threshold=threshold, overlap=overlap, permute=permute)
  File "C:\Users\user\Desktop\3DUnetCNN-master\unet3d\prediction.py", line 129, in run_validation_case
    patch_shape = tuple([int(dim) for dim in model.input.shape[-3:]])
  File "C:\Users\user\Desktop\3DUnetCNN-master\unet3d\prediction.py", line 129, in <listcomp>
    patch_shape = tuple([int(dim) for dim in model.input.shape[-3:]])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
Closing remaining open files:C:\Users\user\Desktop\3DUnetCNN-master\brats\brats_data.h5...done
```

Of course, I have tried to fix it by using [this fix](https://github.com/ellisdg/3DUnetCNN/issues/59) but it doesn't work, at all. 

I've been trying to bypass this error for the better part of a week and it's killing me.

Thanks for reading.

**Comment by nysuka** [comment]
its saying you are trying to int a tuple with int(dim) since dim is a tuple.
what do you get when you print out each dim when you loop through model.input.shape[-3:]?

**Comment by Brandedahall** [comment]
> 
> 
> its saying you are trying to int a tuple with int(dim) since dim is a tuple.
> what do you get when you print out each dim when you loop through model.input.shape[-3:]?

Hey there,

I fixed the issue by creating a new enviroment and installing Tensorflow 2.0.0, along with the dependencies. The training can be done normally, then I can switch over to predict. It's also super fast.

Thanks though.
