### ISSUE TITLE
Can I use it for training on CT images?

### ISSUE THREAD

**Issue by alice-yi** [ellisdg/3DUnetCNN#226]
I have some lung CT images that I want to try to use this to segment

**Comment by isanjit3** [comment]
Did you had any luck? I am also trying to use it for CT images.

**Comment by wenyalintw** [comment]
Same here, want to use it for LIDC lung nodule segmentation.

**Comment by isanjit3** [comment]
I was able to construct the 3D model and train it. However, the prediction is pretty bad. Every slice detected has something while I expect only the cancerous slices has the none zero values.

Any idea what can I do to reduce them? Below is an example, **Left**: Original Image, **Center**: Ground Truth, **Right**: Prediction
<img width="928" alt="sample_prediction" src="https://user-images.githubusercontent.com/47087642/71537418-c1139b00-28e9-11ea-8c14-9fff60921654.png">

**Comment by Gresliebear** [comment]
I have to try Mask segmentation to reduce the number of pixels it could help, I have not applied this model yet.
