### ISSUE TITLE
Preprocessing file and windows adaptibility

### ISSUE THREAD

**Issue by jorgetheman123** [ellisdg/3DUnetCNN#227]
I'm trying to run it on Windows because I don't have Linux yet, does this program adapt for Windows or is it Linux-specific?

Also, after importing the convert_brats_data and using it on my data/original directory, it simply doesn't run. Here's what happens(note: it also comes with a warning but I guess it isn't relevant for my specific problem:

C:\Users\Jorge\Desktop\3DUnetCNN-master\brats>python
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from preprocess import convert_brats_data
C:\Users\Jorge\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will
be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may ne
ed to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Using TensorFlow backend.
>>> convert_brats_data("C:/Users/Jorge/Desktop/3DUnetCNN-master/brats/data/original","C:/Users/Jorge/Desktop/3DUnetCNN-master/brats/data/preprocessed")
>>>

Yet it doesn't execute the code as it should.

**Comment by isanjit3** [comment]
You can create a python file (say test.py) with the following lines;
`from preprocess import convert_brats_data
convert_brats_data("C:/Users/Jorge/Desktop/3DUnetCNN-master/brats/data/original","C:/Users/Jorge/Desktop/3DUnetCNN-master/brats/data/preprocessed")`

Then run it as "python test.py"
Make sure to add the project path in the PYTHONPATH environment variable.

**Comment by wjj001-dl** [comment]
it doesn't works when i run "convert_brats_data("C:/Users/Jorge/Desktop/3DUnetCNN-master/brats/data/original","C:/Users/Jorge/Desktop/3DUnetCNN-master/brats/data/preprocessed")"
