### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'set_image_dim_ordering'

### ISSUE THREAD

**Issue by woctezuma** [ellisdg/3DUnetCNN#228]
There is an error message when running `train.py` in the `brats/` folder. [Apparently](https://github.com/keras-team/keras/issues/12649#issuecomment-533589382), this happens with versions of Keras 2.2.5 and above. I suggest setting Keras version to 2.2.4 in `requirements.txt` or changing the culprit line with one of the suggested changes in the linked issue.

```
AttributeError                            Traceback (most recent call last)

<ipython-input-52-ab33c6d83f33> in <module>()
      2 from unet3d.generator import get_training_and_validation_generators
      3 from unet3d.model import unet_model_3d
----> 4 from unet3d.training import load_old_model, train_model
      5 
      6 def main(overwrite=False):

/content/3DUnetCNN/unet3d/training.py in <module>()
      9                             weighted_dice_coefficient_loss, weighted_dice_coefficient)
     10 
---> 11 K.set_image_dim_ordering('th')
     12 
     13 

AttributeError: module 'keras.backend' has no attribute 'set_image_dim_ordering'
```

**Comment by isanjit3** [comment]
You should change the line# 11 in training,py to the following:

`K.common.set_image_dim_ordering('th')`
