### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by jorgetheman123** [ellisdg/3DUnetCNN#229]
I'm using the latest version of PyCharm, Python 3.7. As I'm trying to train my model, this error appears:

C:\Users\Jorge\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\externals\joblib\__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
Using TensorFlow backend.
Creating validation split...
Number of training steps:  133
Number of validation steps:  17
Epoch 1/300

Process finished with exit code -1073741819 (0xC0000005)

I even tried changing the image size to (32,32,32) and (64,64,64) but same error...

**Comment by isanjit3** [comment]
Looks like you are running out of memory. Did you try changing the batch_size?

**Comment by littlelk** [comment]
same problem.......

**Comment by ljljlj02** [comment]
same problem

**Comment by ljljlj02** [comment]
pip install Keras ==2.1.6 ,or switch to the version of Keras that works for you.
