### ISSUE TITLE
Creating labels on own data

### ISSUE THREAD

**Issue by norapixel** [ellisdg/3DUnetCNN#237]
What tools can be used to annotate dicom slices? 

While working with 2D slices, I had annotated Dicoms by converting them to image formats. However, to be able to retain affine information, wanted to know the tools to label Dicoms directly.

Thanks!

**Comment by insomnia33** [comment]
There are a lot of tools for that, the ones I use most are:
- MeVisLab -> graphic interface to create workflows with image processing functions, check the forum for workflow examples for medical images annotations.
https://www.mevislab.de/

- ITK-SNAP -> easy to use, good extension support and you can find tutorials on youtube.
http://www.itksnap.org/pmwiki/pmwiki.php?n=Main.HomePage
