### ISSUE TITLE
UPF students doubt!

### ISSUE THREAD

**Issue by olalla1999** [ellisdg/3DUnetCNN#239]
![Logo_UPF](https://user-images.githubusercontent.com/64593570/83336292-7b9d3480-a2b2-11ea-9cb0-92c0e0ce290b.jpg)

Hello David!

We are a students team from University Pompeu Fabra (Barcelona). It's the first time we work with ML algorithms and for the final project of one subject we have to "accomplish" the challenge we want. In our case, we've decided to go for BraTS Challenge! We've already preprocessed the MRI from BraTS-2019 and trained the algorithm thanks to your open source code. Nevertheless, we'd like to apply some changes to it in order to get a more personalized algorithm. What changes would you recommend us to perform? (it does not matter if the dice score is lower) Maybe adjust some parameters? Apply a different tool instead of ReLU?

We hope everything is going alright, thank you for reading!

Maria, Ricard, Dani and Olalla

**Comment by ellisdg** [comment]
Hello!

You could try different augmentation strategies, such as blurring the input
image, adding more noise, randomly shuffling input channels, etc. You could
also add in a drop out layer to try and  make the feature channels more
independent. If you want to switch the ReLu activations, you could try a
leaky ReLu and see if it helps or hurts. You could also try changing depth
size of the network, the number of channels, etc.
I hope this gives you guys some ideas! Really there is a whole bunch of
stuff you can try.
Good luck!

**Comment by olalla1999** [comment]
First of all, thank you so much for answering that fast!

Yesterday we got our first results after one week running the code :) (our computers are not that good). We are surprised that our predicted segmentations don't show 4 different labels, but only 2: the whole tumor and the background. We don't know why.

![validation_scores_boxplot](https://user-images.githubusercontent.com/64593570/83605361-0d899380-a578-11ea-9fab-a721c90fe4aa.png)

Besides, thank your for your ideas! We think we are know going to try adding one more unit to the depth (5-->6) and may be adding one more convolution layer to each block. By block I mean depth-block. Also, we were thinking about adding a max pooling layer because when we were learning what a UNet was, convolution and maxpooling were the main two types of layers, if I am not wrong. Finally, we will also try to replace the whole UNet model by a VNet model.


Best regards,

Maria, Ricard, Dani and Olalla
