### ISSUE TITLE
Running predict.py

### ISSUE THREAD

**Issue by selamgit** [ellisdg/3DUnetCNN#243]
After successfully trained the model using my own dataset (i used train_isensee2017.py, model isensee_2017_model.h5 already created, number of label during training was 1). 

I run predict.py

Traceback (most recent call last):
  File "predict.py", line 26, in <module>
    main()
  File "predict.py", line 22, in main
    output_dir=prediction_dir)
  File "/tf/3DUnetCNN/unet3d/prediction.py", line 163, in run_validation_cases
    threshold=threshold, overlap=overlap, permute=permute)
  File "/tf/3DUnetCNN/unet3d/prediction.py", line 124, in run_validation_case
    image = nib.Nifti1Image(test_data[0, i], affine)
IndexError: index 1 is out of bounds for axis 1 with size 1
Closing remaining open files:/tf/3DUnetCNN/brats/brats_data.h5...done

How to fix it ?

**Comment by selamgit** [comment]
Since I was using train_isensee2017, config should be changed in predict as well, its fixed like below:

in predict.py

change:
from train import config

to:
from train_isensee2017 import config

**Comment by TliliFadhila** [comment]
the training is taking 2 days from me and still running with the last instruction: Please use Model.fit, which supports generators.
is there a problem,  if not how much time it took from you?
