### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = '/home/damu/3DUnetCNN-master/brats/tumor_segmentation_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by Iamyourbaba** [ellisdg/3DUnetCNN#246]
OSError: Unable to open file (unable to open file: name = '/home/damu/3DUnetCNN-master/brats/tumor_segmentation_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
 I follow step 1-6 and step 6 show 
Epoch 00059: ReduceLROnPlateau reducing learning rate to 3.906250185536919e-06.
Epoch 00059: early stopping
maybe the train model work well
however,when I python predict.py(step 7), the linux terminal show 
OSError: Unable to open file (unable to open file: name = '/home/damu/3DUnetCNN-master/brats/tumor_segmentation_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
I can not find tumor_segmentation_model.h5. I don not know how to solve the problem. 
Thank you

**Comment by parvezamu** [comment]
you can do this .....just type mv isensee_2017_model.h5 tumor_segmentation_model.h5 on terminal.....and run python predict.py .....if you want to continue the training.......just type overwrite to False.....and mv tumor_segmentation_model.h5  isensee_2017_model.h5.........and then python train_isensee2017.py......
