### ISSUE TITLE
Using higher resolution 3D image for training

### ISSUE THREAD

**Issue by norapixel** [ellisdg/3DUnetCNN#248]
Has anyone tried using multiple GPU's, to train, with batch size of 1; as with higher resolution memory is exhausted. I tried using patch wise training. However I observed better predictions, on using entire image (though lower in resolution) for my particular dataset.

**Comment by ellisdg** [comment]
@norapixel are you hoping that using multiple GPUs will allow you to train on bigger images? I use multiple GPUs but I just use them for "data parallelism", which allows for bigger batch sizes and faster training. If you want to use a batch size of one and have the training split over multiple GPUs that is called "model parallelism". It requires you to put one part of your model one GPU and another part of your model on another GPU. I haven't done this before, but I found this blog that talks about it:
https://data-flair.training/blogs/keras-multi-gpu-and-distributed-training/

**Comment by norapixel** [comment]
@ellisdg Thank you for your response. Yes, I was pointing at model parallelism. I will need to read more about implementation.

Anyways, respect and kudos to you for this repository.
