### ISSUE TITLE
could some one help me?

### ISSUE THREAD

**Issue by sima97** [ellisdg/3DUnetCNN#251]
could someone tell me the sequence of the code?

**Comment by ellisdg** [comment]
What do you mean by the sequence?

**Comment by sima97** [comment]
for example  which folder should I use brats or unet3d?

**Comment by ellisdg** [comment]
Use the brats folder.

**Comment by sima97** [comment]
Thank you for answering me.

**Comment by sima97** [comment]
sorry could I have your email?
