### ISSUE TITLE
N4BiasFieldCorrection

### ISSUE THREAD

**Issue by KrzysztofKotowski** [ellisdg/3DUnetCNN#26]
Installation of ANTs can be omitted by using N4BiasCorrection from SimpleITK http://simpleitk.readthedocs.io/en/master/Examples/N4BiasFieldCorrection/Documentation.html

**Comment by ellisdg** [comment]
Thanks for the suggestion! The problem is I found in practice is that the SimpleITK implementation takes much much longer than the ANTs version.

**Comment by KrzysztofKotowski** [comment]
Ok thanks, good to know. Issue closed.
