### ISSUE TITLE
data.py file 

### ISSUE THREAD

**Issue by zhoutonxgue** [ellisdg/3DUnetCNN#267]
Hi, where can I find back the data.py and other related files, I remember I can see it last year, thank you very much.

**Comment by ellisdg** [comment]
I moved those files to the "legacy" folder. I plan on removing them in the future, but will keep them there in case people still want access to them.

**Comment by zhoutonxgue** [comment]
I see, thank you for your quick reply, the work is very interesting, thanks again : ）
