### ISSUE TITLE
Missing library

### ISSUE THREAD

**Issue by riep** [ellisdg/3DUnetCNN#268]
Hi,
I looking forward to test your implementation of 3DUNET. However I have the following inhouse library that is not found.

from unet3d.scripts.predict import format_parser as format_prediction_args, check_hierarchy
ImportError: cannot import name 'check_hierarchy'

I cannot find it in the repository

**Comment by ellisdg** [comment]
Thanks for pointing this out! I had removed that function from the predict.py file but I had forgotten that the train.py file used that function as well.
