### ISSUE TITLE
Slack group invitation link is no longer active

### ISSUE THREAD

**Issue by ysam12345** [ellisdg/3DUnetCNN#272]
Would like to join the slack group but the link provided at https://github.com/ellisdg/3DUnetCNN#got-questions seems not active.
![image](https://user-images.githubusercontent.com/28039402/100257847-56e3fa00-2f81-11eb-8e1c-f90fd89bc241.png)

Thanks!

**Comment by ellisdg** [comment]
You're right. I didn't realize the links expire after 30 days.

Here is the new one:
https://join.slack.com/t/3dunet/shared_invite/zt-jt61n5jk-npXtxVRkThldgFePVYi9lA

**Comment by ellisdg** [comment]
Let me know if the new link works for you.

**Comment by ysam12345** [comment]
> Let me know if the new link works for you.

Yes it works for me. Thank you!

**Comment by Gresliebear** [comment]
it expired again sorry

**Comment by Gresliebear** [comment]
could you repost it
