### ISSUE TITLE
Train

### ISSUE THREAD

**Issue by wenhankang** [ellisdg/3DUnetCNN#275]
When i am traing 
Epoch 1/500

tensorflow.python.framework.errors_impl.InvalidArgumentError:  Conv3DBackpropInputOpV2 only supports NDHWC on the CPU.
	 [[node gradient_tape/model/conv3d_29/Conv3DBackpropInputV2 (defined at /pycharm_project/3DUnetCNN_test/legacy/unet3dlegacy/training.py:80) ]] [Op:__inference_train_function_21604]

Function call stack:
train_function
Anyone's answer would be appreciated

**Comment by wenhankang** [comment]
When i set K.set_image_data_format("channels_first") in unet.py
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Conv3DBackpropInputOpV2 only supports NDHWC on the CPU.
When i set K.set_image_data_format("channels_last") in unet.py
ValueError: Operands could not be broadcast together with shapes (14, 64, 64, 3) (16, 64, 64, 3)
Can you help me ? really appreciate

**Comment by ellisdg** [comment]
Do you have tensorflow-gpu installed?

Like you tried, this [thread ](https://github.com/Rayhane-mamah/Tacotron-2/issues/73)suggests switching to "channels_last", but the code was built to run with channels first, so it is not surprising that you would get errors. You could follow the errors to change all the parts that assume the channels are first.

**Comment by wenhankang** [comment]
I used tensorflow 2.2.0.
I am very glad to receive your reply. I will try to modify the code

**Comment by Nhunguts** [comment]
I met exactly this problem. @wenhankang  have you solve this and how? Thank you.

**Comment by wenhankang** [comment]
I read the auther's comment,but I didn't solve the problem.I'm sorry I couldn't help you.
