### ISSUE TITLE
no data loaded

### ISSUE THREAD

**Issue by 1alebra2** [ellisdg/3DUnetCNN#278]
I run the following command and get
 python3 ../../unet3d/scripts/predict.py --segment --output_directory ./predictions/validation/baseline --config_filename ./brats_config.json --model_filename ./brats_unet3d_baseline.h5 --replace Training Validation --group validation --output_template "BraTS20_Validation_{subject}.nii.gz" --nthreads 12 --ngpus 1 

2020-12-18 10:31:26.618626: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Config:  ./brats_config.json
{'n_workers': 12, 'n_gpus': 1, 'use_multiprocessing': True, 'pin_memory': False, 'directory': ''}
Model:  ./brats_unet3d_baseline.h5
Output Directory: ./predictions/validation/baseline
model
./brats_unet3d_baseline.h5 4
0
Encoder 0: 4 32
Encoder 1: 32 64
Encoder 2: 64 128
Encoder 3: 128 256
Encoder 4: 256 512
Decoder 4: 512 256
Decoder 3: 512 128
Decoder 2: 256 64
Decoder 1: 128 32
Decoder 0: 64 32

Dataset: 0

Tried a lot of things. no avail.  Any help appreciated

**Comment by ellisdg** [comment]
Can try checking out the "debug" branch and then adding "--debug" to the command? This should raise an error that gives the filenames that it is failing to load.

**Comment by 1alebra2** [comment]
sorry,. but debug does not work.  I pulled the code, 30 min. ago.
I guess it is the brat_confog.json.
I tried all variants for the data files including the absolute paths, what you use in the autoimplant2020.
the last variant was:  

  "subjects_filename": "examples/brats2020/brats_subjects_2020.json",
  "generate_filenames": "templates",
  "generate_filenames_kwargs": {
    "directory": "examples/brats2020//MICCAI_BraTS2020_TrainingData/BraTS20_Training_{subject}",
    "feature_templates": [
      "BraTS20_Training_{subject}_t1.nii.gz",
      "BraTS20_Training_{subject}_t1ce.nii.gz",
      "BraTS20_Training_{subject}_flair.nii.gz",
      "BraTS20_Training_{subject}_t2.nii.gz"
    ],
    "target_templates": "BraTS20_Training_{subject}_seg.nii.gz"
  },

I have not the slighest idea.  By the way train.py complains as well about  "but got num_samples=0"

**Comment by ellisdg** [comment]
The way it is setup is to go through the subjects in the [brats_subjects_2020.json](https://github.com/ellisdg/3DUnetCNN/blob/master/examples/brats2020/brats_subjects_2020.json) file and then to find the filenames for that given subject. It generates the filenames joining the directory with the filenames and putting the subject_id in "{subject}" space. However, you can override the feature to generate the filenames. For the validation filenames you can add a key value pair for "validation_filenames" where validation filenames is a list of the input filenames. For example:
```
config["validation_filenames"] = [ [
    ["/path/to/your/brats/data/subject_folder/BraTS20_Validation_001_t1.nii.gz",
     "/path/to/your/brats/data/subject_folder/BraTS20_Validation_001_t1ce.nii.gz",
     "/path/to/your/brats/data/subject_folder/BraTS20_Validation_001_flair.nii.gz",
     "/path/to/your/brats/data/subject_folder/BraTS20_Validation_001_t2.nii.gz"], None, None, None, "001"] ]
```
The "None" values are just placeholders for features that aren't used for this example. The "001" is the subject id which is used when writing the prediction to the target template. This way you can write a line for every input subject in the dataset, and the filename generation will be overwritten.

Also, you don't have to use the key "validation_filenames". You can pass whatever group name you want to the prediction script. The script looks for the group name + "_filenames" key in the configuration. If it does not exist, then it will attempt to generate the filenames given the configuration parameters.

**Comment by 1alebra2** [comment]
I wish you a good start in the new year. Thanks for your help. I finally got it up and running.
However, where would I have  to insert the code snippet you mentioned when predicting my own patients and what to remove?
If I wanted to train with more the 3 segments I would only have to change  "n_features": in the config.json?

**Comment by ellisdg** [comment]
n_features is the number of images that is the number of input images. In the BraTS data we have 4, T1w, T1w contrast enhanced, T2w, and FLAIR. "[n_outputs](https://github.com/ellisdg/3DUnetCNN/blob/master/examples/brats2020/brats_config.json#L49)" is the number of segmentation maps to generate.

To train on your own data, you just need to point the [directory](https://github.com/ellisdg/3DUnetCNN/blob/master/examples/brats2020/brats_config.json#L5) and [feature templates](https://github.com/ellisdg/3DUnetCNN/blob/master/examples/brats2020/brats_config.json#L6) to point to your image files.

**Comment by 1alebra2** [comment]
Thanks a lot. I got all working already

> Am 12.01.2021 um 19:02 schrieb David G Ellis <notifications@github.com>:
> 
> ﻿
> n_features is the number of images that is the number of input images. In the
BraTS data we have 4, T1w, T1w contrast enhanced, T2w, and FLAIR. "n_outputs"
is the number of segmentation maps to generate.
> 
> To train on your own data, you just need to point the directory and feature
templates to point to your image files.
