### ISSUE TITLE
What's the version of keras, and how to install it?

### ISSUE THREAD

**Issue by zhonhel** [ellisdg/3DUnetCNN#284]
I install keras by run:

`pip install tensorflow`

After this command, I installed tensorflow-2.5.0, and keras_nightly-2.5.0, and keras_preprocessing-1.1.2

In this situation，when I run the command in https://github.com/ellisdg/3DUnetCNN/tree/master/examples/brats2020,
`python ../../unet3d/scripts/predict.py --segment --output_directory ./predictions/validation/baseline --config_filename ./brats_config_auto.json --model_filename ./brats_unet3d_baseline.h5 --replace Training Validation --group validation --output_template "BraTS20_Validation_{subject}.nii.gz" --nthreads 1 --ngpus 1`

I got the error:
`ImportError: cannot import name 'Sequence' from 'keras.utils'`

Can you help to solve this issue?
Thank you very much!

**Comment by zhonhel** [comment]
Could the author knidly give a requirments.txt?

**Comment by ellisdg** [comment]
I used keras 2.4.3 installed using pip.

Looking at the API, it looks like the Sequence class is still in Keras utils:
https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence

Maybe the issue is with the nightly version of keras? You could also just change the import from 'keras.utils' to 'tf.keras.utils', and I'm guessing that would work.

**Comment by JianhuanZhuo** [comment]
> I used keras 2.4.3 installed using pip.
> 
> Looking at the API, it looks like the Sequence class is still in Keras utils:
> https://www.tensorflow.org/api_docs/python/tf/keras/utils/Sequence
> 
> Maybe the issue is with the nightly version of keras? You could also just change the import from 'keras.utils' to 'tf.keras.utils', and I'm guessing that would work.

Would be kind to provide the requirement.txt with the certain version of dependencies work?

**Comment by ellisdg** [comment]
See #288 for information on requirements and updates I have done to the code to try and remove Keras. I was able to run training with only installing Pytorch and NiLearn.

Here is an environment that I used to run training on the AutoImplant data:
https://github.com/ellisdg/3DUnetCNN/blob/master/examples/autoimplant2020/autoimplantenv.yml
