### ISSUE TITLE
Request of Requirements.txt

### ISSUE THREAD

**Issue by SantaFlang** [ellisdg/3DUnetCNN#288]
Can anybody give a Requirements.txt? That's bloody confused for new guy to run this code. THX a lot

**Comment by ellisdg** [comment]
I cleaned up some things and now I am able to run training after installing Pytorch and nilearn. You can find instructions for installing these tools at their respective websites. I have not included a requirements.txt doc because PyTorch is not recommended to be installed via pip.

**Comment by ellisdg** [comment]
I have added a configuration file for the environment that I used.
https://github.com/ellisdg/3DUnetCNN/blob/master/examples/autoimplant2020/autoimplantenv.yml

**Comment by SantaFlang** [comment]
THX for your reply! That really helps! But now I have one more question to bother you, which is that when I run the train.py the occupancy rate of my GPU is nearly 0%. Is that normal? Hope for your reply, THX again.

**Comment by ellisdg** [comment]
When you run 'nvidia-smi' do the Python processes show as being run on your GPU?

**Comment by SantaFlang** [comment]
Yes, I checked it and It seems like not being run on GPU. But I do have a 3080 and install the pytorch for cuda.

**Comment by SantaFlang** [comment]
I use the code to test my PyTorch
`import torch
 
print(" pytorch_version{}".format(torch.__version__))
print("\nCUDA is avaiable:{}, version is {}".
        format(torch.cuda.is_available(), torch.version.cuda))
print("\n device_name:{}".format(torch.cuda.get_device_name(0)))`
and it showed like
` pytorch_version1.4.0
CUDA is available:True, version is 9.2
 device_name:NVIDIA GeForce RTX 3080`
