### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by mavaylon1** [ellisdg/3DUnetCNN#296]
I think it would be cleaner if you had separate repositories for pytorch and keras. You also have multiple files sharing a name that makes it confusing to keep track. for example, under the unet3d folder you have a train.py in the scripts folder and the train folder. Also I can only find unet for pytorch under segmentation but not with keras. Why have both if they're not going to be held at the same level, which goes back to having separate repos if the keras version is still being developed.

**Comment by ellisdg** [comment]
You are right. I have been slowing trying to do away with Keras, but haven't gotten to fully getting rid of it. It's on my todo list. I think it is a good idea to make a legacy repository with the old version that was based on Keras.

The repository is basically the tool that I use for all of my deep learning projects. So as I have moved away from Keras to PyTorch, there are just some fragments of stuff that I need to delete.
