### ISSUE TITLE
I’d like to know the isensee2017 and isensee2017_model are two 3DUNet?

### ISSUE THREAD

**Issue by bogeyixiu** [ellisdg/3DUnetCNN#297]
3DUnetCNN-master\legacy\brats\train.py  using new model "isensee2017_model".However I can't find it,I just find 3DUnetCNN-master\legacy\unet3dlegacy\model\isensee2017.py

> Thank you very much for your reply to my message. I'm sorry to ask a stupid question😱😱😱. I have just come into contact with research in this field and am studying your ideas. Your idea of designing the network is very creative. I hope we can continue to communicate in the future.😃😃😃

**Comment by ellisdg** [comment]
What is the output printed to screen from the train.py script?
