### ISSUE TITLE
 load_subject_ids(config)

### ISSUE THREAD

**Issue by maralzar** [ellisdg/3DUnetCNN#298]
I am trying to run this code, I get this error
File "../../unet3d/scripts/predict.py", line 203, in <module>
    main()
  File "../../unet3d/scripts/predict.py", line 51, in main
    run_inference(namespace)
  File "../../unet3d/scripts/predict.py", line 97, in run_inference
    load_subject_ids(config)
TypeError: load_subject_ids() missing 1 required positional argument: 'name'
 and in the code I checked, I saw that this function in the forecast file needs two variables to pass
load_subject_ids(config)
, but a given variable, how can I do this?

**Comment by Ron-carry** [comment]
Hi~ I also meet this question: 

---------------------------------------------------------------------------------
Traceback (most recent call last):
  File "../../unet3d/scripts/predict.py", line 206, in <module>
    main()
  File "../../unet3d/scripts/predict.py", line 56, in main
    run_inference(namespace)
  File "../../unet3d/scripts/predict.py", line 101, in run_inference
    load_subject_ids(config)
TypeError: load_subject_ids() missing 1 required positional argument: 'name'
---------------------------------------------------------------------------------

Have you addressed it?  I want to know how make it.

**Comment by minaavazbeigi** [comment]
I have the same error. have you found any solution?

**Comment by minaavazbeigi** [comment]
I simply change line ` load_subject_ids(config)` to ` load_subject_ids(config, 'test')` in predict.py file in path `unet3d/scripts/predict.py` ! while I'm not using `subjects_filename` in my config, nothing goes wrong but the error does not show up again! I'm not suggesting this to those using `subjects_filename` in their config!

**Comment by ellisdg** [comment]
Ok, this should be fixed now with the latest update. Reopen this issue if the problem persists.
