### ISSUE TITLE
evaluate 3dunet with pytorch

### ISSUE THREAD

**Issue by maralzar** [ellisdg/3DUnetCNN#299]
hi i want to evaluate the pytorch code how can i do this ?

**Comment by Ron-carry** [comment]
Maybe you want to evaluate the prediction and truth . I am also attempting this ! My thinking is：
Maybe you can make use of the project's own code : legacy/brats/evaluate.py , which has the calculation of dice coefficient. Of course, there is similar code in other places in the project !

**Comment by fzadib** [comment]
Thank you very much for answering
I intend to run the code with the torch and I used the same file you said and I even used the pre-trained model, but my results are not good at all. Do you get good results?
