### ISSUE TITLE
keras-contrib version

### ISSUE THREAD

**Issue by nick917** [ellisdg/3DUnetCNN#30]
Hi,

In 'requirements.txt', keras_contrib>=1.2.1
I installed the one at https://github.com/farizrahman4u/keras-contrib and it shows 0.0.2
(upgrade does not help)

Do you know where I can find 1.2.1 version?

Thanks

**Comment by ellisdg** [comment]
That was a mistake on my part. Thanks for pointing this out! The requirements.txt file should now be correct.
