### ISSUE TITLE
KeyError: 'config' during evaluation on brats example

### ISSUE THREAD

**Issue by tarekegn82** [ellisdg/3DUnetCNN#317]
Dear @ellisdg,

I am running inference on brats2020 and I couldn't figure out what the issue is here because there are labels config inside `config_filename` as shown below
`"dataset": {
        "name": "SegmentationDatasetPersistent",
        "desired_shape": [
            128,
            128,
            128
        ],
        "labels": [
            2,
            1,
            4
        ],
`

But the error persists even if I have tried to solve by adding `dataset_config = config.get("dataset", {})`

Please let me know if you can see through this issue.

Thank you

**Comment by tarekegn82** [comment]
` labels = config["labels"]
KeyError: 'labels'`

here it is.

**Comment by tarekegn82** [comment]
Dear @ellisdg 

I hope you are alright. Another similar issue has been opened about the evaluation phase. Please reply to either one of us when you have time.

Thank you.

**Comment by ellisdg** [comment]
The evaluate.py script has been deleted. See #319. If there is enough interest I might work on writing a new evaluate.py script in the future, so let me know!
