### ISSUE TITLE
An error occurred during the evaluation

### ISSUE THREAD

**Issue by liaochuanlin** [ellisdg/3DUnetCNN#319]
/home/aa/anaconda3/envs/unet3d/bin/python3.9 /home/aa/3DUnetCNN/unet3d/scripts/evaluate.py --directory /home/aa/3DUnetCNN/examples/brats2020/brats2020_config/fold1/validation --output_filename /home/aa/3DUnetCNN/examples/brats2020/brats2020_config/output/output.csv --config_filename /home/aa/3DUnetCNN/examples/brats2020/brats2020_config.json 
Traceback (most recent call last):
  File "/home/aa/3DUnetCNN/unet3d/scripts/evaluate.py", line 91, in <module>
    main()
  File "/home/aa/3DUnetCNN/unet3d/scripts/evaluate.py", line 68, in main
    labels = config["labels"]
KeyError: 'labels'

Process finished with exit code 1

**Comment by ellisdg** [comment]
I apologize, the evaluate script is out of date. It will be deleted with a pull request that I am working on. For now, evaluation is not a feature of the repository. If you or someone else would like to add an updated evaluate.py script, that would be great!
See #316 for an example of how to compute performance metrics.
This is the same issue as #317.

**Comment by ellisdg** [comment]
I am going to close this issue as the `evaluate.py` script has been deleted.
