### ISSUE TITLE
The train.py seems no args of "model_filename" and "training_log_filename"

### ISSUE THREAD

**Issue by yibingchen2023** [ellisdg/3DUnetCNN#326]
When I run training process as quick start, I met this error: "train.py: error: unrecognized arguments: --model_filename final_model.pth --training_log_filename training_log_20231023.txt".

How can I get the training log?

**Comment by ellisdg** [comment]
Thanks for pointing this out. I have updated the scripts, but I forgot to update the README. Checkout the [Brats 2020 example](https://github.com/ellisdg/3DUnetCNN/tree/master/examples/brats2020) for how to run the training.

**Comment by yibingchen2023** [comment]
Thanks for your answer. I found that "model_filename" and "training_log_filename" can be written to the training json file, just like:
config["training_log_filename"] = "training_log.csv"
config["model_filename"] = "model_final.pth"
Note that, training_log is csv file not txt file.
Moreover, the cross validation must be closed, as below:
# config["cross_validation"] = {'folds': 1,  # number of cross validation folds
#                               'seed': 25},  # seed to make the generation of cross validation folds consistent across different trials
