### ISSUE TITLE
I'm really sorry for bothering you

### ISSUE THREAD

**Issue by 111678900** [ellisdg/3DUnetCNN#333]
![718b1af33889dbe20441f44aa34227f](https://github.com/ellisdg/3DUnetCNN/assets/152053751/f281c4ee-15f9-4a38-9c3f-06611061f6a5)
I'm really sorry for bothering you，I'm using it to train in my own dataset.Discovering these images in the example folder after training, does it mean that the training was successful?"If it is successful, how should I run the predict.py file?

**Comment by ellisdg** [comment]
Those are 3D renderings that I made as an example of skull completion using the AutoImplant dataset.

You should have a training log file that you can look at to see how many epochs were run and if the training and validation losses decreased like you would expect.

**Comment by 111678900** [comment]
&nbsp;So it has already succeeded？



---Original---
From: "David G ***@***.***&gt;
Date: Thu, Jan 18, 2024 04:43 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ellisdg/3DUnetCNN] I'm really sorry for bothering you (Issue#333)




 
Those are 3D renderings that I made as an example of skull completion using the AutoImplant dataset.
 
You should have a training log file that you can look at to see how many epochs were run and if the training and validation losses decreased like you would expect.
