### ISSUE TITLE
Unable to clone

### ISSUE THREAD

**Issue by tarekegn82** [ellisdg/3DUnetCNN#334]
@ellisdg Recently, I couldn't clone this repository for an unknown reason. is there any solution from your side, please?

**Comment by ellisdg** [comment]
Typing ```git clone https://github.com/ellisdg/3DUnetCNN``` worked for me. Do you have any more information about the error you are getting?

**Comment by tarekegn82** [comment]
Solved it, I use proxy server so it’s causing the problem. I changed my vpn
so it works now




*TAREKEGN*
