### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by NongXuXuan** [ellisdg/3DUnetCNN#338]
Traceback (most recent call last):
  File "/home/user/3DUnetCNN/unet3d/scripts/train.py", line 7, in <module>
    from .train import run_training
ImportError: attempted relative import with no known parent package

**Comment by ellisdg** [comment]
Looking at the `3DUnetCNN/unet3d/scripts/train.py` file, I don't see `from .train import run_training`. Are you using an old version of the repository?

https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/scripts/train.py#L7

**Comment by NongXuXuan** [comment]
thx for replying. I set my script path incorrectly. I have solved it now. I am now trying to predict my data. I am appreciate your support.
