### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by User-Ali** [ellisdg/3DUnetCNN#35]
Don't know whether should I post here. I didn't find you email too for the contact.

I need a pretrained model from your implementation. So, can you please upload a pre-trained model?

**Comment by ellisdg** [comment]
Sorry, I don't want to make my trained models publicly available at this time. Have you tried using my code to train your own models?

**Comment by RafiaRahim** [comment]
Hi,
Is it possible to share pre-trained model now?
