### ISSUE TITLE
Implementation of label map and viewing prediction.nii.gz

### ISSUE THREAD

**Issue by build2create** [ellisdg/3DUnetCNN#36]
@ellisdg The file is produced after successfully running predict.py. But the label map (which I am assuming is prediction.nii.gz) is not multicolor. I have tried itk snap and 3D slicer. I am not able to understand how is multiclass classification is implemented. Is the tumor detected using 3D unet also segmented?If yes,does the label map give different colors to segmented portions of the tumor. For e.g. red to necrotic, blue to advancing and so on. Please suggest any other tool or alternatively can you post the screenshot of the segmented image? 

Here is the screenshot of what I got using model trained with config["image_shape"]=(16,16,16). This is using itk snap:
![image](https://user-images.githubusercontent.com/25721143/30096530-79cfeb58-92f6-11e7-958d-f6362354cfe6.png)
And this one using 3D slicer:
![image](https://user-images.githubusercontent.com/25721143/30096577-c88d0e60-92f6-11e7-8ca1-022e546dfc11.png)

**Comment by viveknimbarmunde** [comment]
I built the model for 50 epochs but still getting the prediction.nii.gz as blank(nothing is shown up). data_T1.nii.gz is showing segmentation in red and green colors. What do these colors indicate? Do they indicate various types like necrotic,advancing regions of same tumor? Also suggest any good tool for viewing the segmented image. Can you post any sample of predicted(segmented) image?
