### ISSUE TITLE
Can you please provide more training examples?

### ISSUE THREAD

**Issue by edraizen** [ellisdg/3DUnetCNN#37]
BRATS and iSeg all require registration. I would like to see an example so I know how to format my data. Thanks!

**Comment by ellisdg** [comment]
Is there a particular freely available dataset that you would like an example for?

**Comment by edraizen** [comment]
Hey, sorry for the delay in responding. I was able to get a simple sphere predictor to work to predict spheres from random noise, which works well. If you're interested, you can see it here: https://github.com/edraizen/3DUnetCNN/blob/master/spheres/train.py
