### ISSUE TITLE
3d vessel Segmentation and Testing issue

### ISSUE THREAD

**Issue by arielluluh** [ellisdg/3DUnetCNN#40]
Hi @ellisdg 
I am doing 3d image segmentation for detection stenosis and plague of vessel inside coronary artery. Can I use the code that you provided? My dataset format is also in Nifti format but only one modality. Besides, will you provide the testing code for this 3d unet segmentation example?

Thank you for your time:)

**Comment by ellisdg** [comment]
I don't know anything about your dataset, so I can't really write code to test it. Does your dataset have a ground truth?

**Comment by arielluluh** [comment]
yes. I have a ground truth. Or could you code to test your BRATS dataset as an example. So that I may have a idea how to do the testing:)

**Comment by ellisdg** [comment]
Check out this [file](https://github.com/ellisdg/3DUnetCNN/blob/master/iseg/train.py). It specifies the training/network configuration, collects the data, and then runs the network training. You can modify that file to run the training on your data. Is that what you are asking?

**Comment by arielluluh** [comment]
Actually I am asking about the testing process after we have done the training. Because I saw the dataset you provided include both training data and testing data. But the code are all for training. Do you have the code for testing?
