### ISSUE TITLE
Testing of the model

### ISSUE THREAD

**Issue by build2create** [ellisdg/3DUnetCNN#41]
Hello @ellisdg  Can you provide some inputs on how to view prediction.nii.gz that is generated after testing. Also please explain what is multi-class classification is doing exactly? I guess it is producing the label map but when I see the image in ITK Snap I can see only red aand green patches in the image. Any help in this regard is greatly appreciated.

**Comment by ellisdg** [comment]
Did you train your model to predict multiple classes?

**Comment by build2create** [comment]
Yes we did the training with the exact same code you last committed.
