### ISSUE TITLE
I can`t download the data,can u help me?

### ISSUE THREAD

**Issue by Lilylilililili** [ellisdg/3DUnetCNN#44]
I`m sorry to trouble u, but i can`t download the data. I try to register in his websize, but failed.  Can u give me the data? I`m a new comer , so I promise it just for learning. Thank u!

**Comment by Philex5** [comment]
Hi! Have you resolved this problem?

**Comment by ellisdg** [comment]
Sorry, the dataset is quite large. I don't think have the resources to host it online so that others can download it.
