### ISSUE TITLE
difference with the model described in the 3D Unet paper?

### ISSUE THREAD

**Issue by snapfinger** [ellisdg/3DUnetCNN#46]
I find in the original paper, there's batch normalization after (almost) each convolution, seems your [code](https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/model.py) does not introduce that?

**Comment by ellisdg** [comment]
That is correct. As mentioned in #39, I am working on a branch that has an option to add batch normalization.  I have implemented batch normalization in a [separate branch](https://github.com/ellisdg/3DUnetCNN/tree/arbitrary_depth) that I am using to test some new features. I had put batch normalization in my code earlier, but I took it out as it required more memory to run training with batch normalization than without it. Feel free to use the testing branch. It seems to work, but I get errors every now and again when I use the patch wise training feature. If you run into any issues with it, let me know.

**Comment by snapfinger** [comment]
Oh sorry I didn't see that issue. Got it, I saw that branch. Thanks for your work!
