### ISSUE TITLE
Could i use this model to solve the CT lung images problems?

### ISSUE THREAD

**Issue by HiImgosuuuu** [ellisdg/3DUnetCNN#48]

**Comment by ellisdg** [comment]
Yes, it should work fine. You will want to use different preprocessing methods. Also, CT lung images can be very big, so you may have to look at splitting the data into patches.

**Comment by b-z** [comment]
@ellisdg Would it work fine if I take a downsampling instead of splitting into patches as you mentioned above?

**Comment by ellisdg** [comment]
Downsampling should work, you would just get a much less precise prediction. (Sorry for the late response)
