### ISSUE TITLE
keras_contrib has removed Deconvolution3D

### ISSUE THREAD

**Issue by mingrui** [ellisdg/3DUnetCNN#56]
https://github.com/farizrahman4u/keras-contrib/commit/a8ec7ad10a9cbf5637198bc6f731788d8d973464

**Comment by ellisdg** [comment]
Thanks for letting me know. You should be able to import it straight from
keras now. I'll try to update it later this week.

**Comment by mingrui** [comment]
Thanks for looking into this!
Yes you are correct we can import it directly from keras, but the input parameters changed.
So the Deconvolution3D function will not run.
I'm a noob at this but I'll try to figure it out.

**Comment by Kivin1** [comment]
Hi,
Have you solved this problem, how to import Deconvolution3D now?
