### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by dbonner** [ellisdg/3DUnetCNN#58]
I get a segmentation fault (core dumped) message after the first epoch is trained.  I had to turn off the Deconvolution3D because it wasn't available from keras_contrib.  I don't know if that has anything to do with the segmentation fault.

CUDA 8, CUDNN 6, 2 x Nvidia 1080 Ti, 64 gigabytes RAM, Python 3.6 virtual environment, Keras 2.1.1

**Comment by mingrui** [comment]
I had the same problem, patch_size 64, batch_size 3, GTX 1080 8 gibs vram.
Take a look at your validation_batch_size, I turned it down to 6.
I think't it's because at the end of each epoch, validation is run and because the validation size is too large, you are out of memory.

**Comment by DongqingZhang** [comment]
Agree with @mingrui . When I met this question and I simply disabled the validation part by changing the training.py file and 'train_model' function a little bit to get quick test since it seems the validation is only used for early stop. And the segmentation fault disappeared

**Comment by dbonner** [comment]
I'm still getting a segmentation fault with a lower batch size and validation_batch_size.  What were the adjustments you made DongqingZhang?

**Comment by DongqingZhang** [comment]
@dbonner What I did is: in function 'train_model' in training.py, delete 'validation_data=validation_generator' and 'early_stopping_patience=early_stopping_patience'. I also added 'max_q_size=2' in this function. Not 100% why these changes work for me cause I googled for other people's advice and it seems to work...

**Comment by mingrui** [comment]
How many modalities are you training with.
Try and change to only one modality at a time and see if it works?

**Comment by dbonner** [comment]
Thanks DongqingZhang,
I adopted your modifications and it works now.

**Comment by mingrui** [comment]
@DongqingZhang I turned on flip and distort = 0.5, started to get seg faults, then deleted 'validation_data=validation_generator' and training worked again.

But there is no validationg loss anymore, do you think the seg fault problem is related the the `validation_generator` ?

**Comment by DongqingZhang** [comment]
@mingrui Indeed, it's not good if we blindly reduce the training error without looking at a val set.
Your guess is reasonable. I will take a look at the validation_generator when I am free.

**Comment by Byronze** [comment]
@DongqingZhang have you solved this problem

**Comment by gatagat** [comment]
The issue is in the way how HDF5 is used through PyTables.

I have found two solutions:
1. call `fit_generator(..., use_multiprocessing=True)`, or
2. recompile the HDF5 library to be thread-safe (see https://support.hdfgroup.org/HDF5/faq/threadsafe.html).

**Comment by mingrui** [comment]
@gatagat I think you are right about this, I tested again with flip and distort = 0.5, and there are no segfaults.

Thank you!

**Comment by kdk411** [comment]
@gatagat gatagat's suggestion worked for me. I turned use_multiprocessing = True (by default, it is false), and it works like magic.

**Comment by kdk411** [comment]
@gatagat Umm, so even after I turned use_multiprocessing=True, i still get problems and trying to use 2 from your suggestions. But I am having some difficulties with the link that you shared. It says that I need to:

`./configure --enable-threadsafe --with-pthread=DIR`

but I am not sure in what directory I need to perform it. Is it under /site-packages/h5py ? ( I looked up there but can't find configure)

**Comment by gatagat** [comment]
Hi Donnie, i think following the option 2. is the right way to go. For that you need to compile the hdf5 from source (detailed explaination: https://support.hdfgroup.org/ftp/HDF5/prev-releases/hdf5-1.8/hdf5-1.8.20/src/unpacked/release_docs/INSTALL) first using the options given above with the configure command. Only afterwards you install h5py from source and tell it to use the your version of HDF5. Be prepared, this might not be easy if you have never compiled anything from source. Good luck!

**Comment by galactica147** [comment]
I tried setting multiprocess=True as suggested above but still got the errors like:

```
...
 File "/usr/local/lib/python3.5/dist-packages/tables/array.py", line 766, in _read_slice
    self._g_read_slice(startl, stopl, stepl, nparr)
  File "tables/hdf5extension.pyx", line 1585, in tables.hdf5extension.Array._g_read_slice
tables.exceptions.HDF5ExtError: HDF5 error back trace
  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 554, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock                                                                                                                                                    
    data pipeline read failed

```
For the option of self-compiling hdf5, i'm not sure how to:
1. make sure it's visible for the python3 executable
2. avoid conflicts with pip3 installed hdf5 (i guess pip3 remove it should be fine).

**Comment by safa94** [comment]
Hi I have the same issue here how did you solve it please?
Thanks in advance

**Comment by cpwardell** [comment]
I think I found a _better_ solution.  I tried rebuilding a nice threadsafe and parallel version of HDF5, but a much simpler and faster solution (which appears to have little to no impact on the execution speed) is to change/remove the compression of the input data when creating the h5 object.

Specifically: in `unet3d/data.py` change this line:

`filters = tables.Filters(complevel=5, complib='blosc')`
to
`filters = tables.Filters(complevel=0)`

That fixed the error for me.

Many thanks to the original author for all their hard work, and to other users for first noticing the HDF5 connection.

**Comment by steelexu** [comment]
see https://github.com/keras-team/keras/issues/8225
set workers=0 to fit_generator, then error disappear, but then only one gpu is running

**Comment by csudage** [comment]
> @dbonner我所做的是：在training.py中的函数'train_model'中，删除'validation_data = validation_generator'和'early_stopping_patience = early_stopping_patience'。我还在此函数中添加了“max_q_size = 2”。不是100％为什么这些变化对我有用，因为我用谷歌搜索其他人的建议，它似乎工作...

**Comment by chestnut111** [comment]
> see [keras-team/keras#8225](https://github.com/keras-team/keras/issues/8225)
> set workers=0 to fit_generator, then error disappear, but then only one gpu is running
it fix it !, but only one GPU,when i use mutil GPU , i occurs this:
```
Epoch 1/500
123/125 [============================>.] - ETA: 11s - loss: -0.0553 - dice_coefficient: 0.05532019-02-28 14:12:40.579127: F tensorflow/stream_executor/cuda/cuda_dnn.cc:521]   
Check failed: 
cudnnSetTensorNdDescriptor(handle_.get(), elem_type, nd, dims.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)batch_descriptor: 
{count: 0 feature_map_count: 64 spatial: 64 64 64  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
Aborted (core dumped)

```

**Comment by tianxz1** [comment]
set workers=0 to fit_generator
Where is the specific setting, I did not find, who can help me

**Comment by tianxz1** [comment]
> see [keras-team/keras#8225](https://github.com/keras-team/keras/issues/8225)
> set workers=0 to fit_generator, then error disappear, but then only one gpu is running

Where is the specific setting, I did not find it, can you help me?

**Comment by lpengc** [comment]
> The issue is in the way how HDF5 is used through PyTables.
> 
> I have found two solutions:
> 
> 1. call `fit_generator(..., use_multiprocessing=True)`, or
> 2. recompile the HDF5 library to be thread-safe (see https://support.hdfgroup.org/HDF5/faq/threadsafe.html).

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
you are a lifesaver! the first resolution works for me!

**Comment by 378978764** [comment]
> @gatagat gatagat's suggestion worked for me. I turned use_multiprocessing = True (by default, it is false), and it works like magic.

But I met the error after doing this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/keras/utils/data_utils.py", line 654, in _data_generator_task
    generator_output = next(self._generator)
  File "/root/shengdi_new/py/3DUnetCNN/unet3d/generator.py", line 155, in data_generator
    skip_blank=skip_blank, permute=permute)
  File "/root/shengdi_new/py/3DUnetCNN/unet3d/generator.py", line 210, in add_data
    data, truth = get_data_from_file(data_file, index, patch_shape=patch_shape)
  File "/root/shengdi_new/py/3DUnetCNN/unet3d/generator.py", line 238, in get_data_from_file
    x, y = data_file.root.data[index], data_file.root.truth[index, 0]
  File "/usr/local/lib/python3.5/dist-packages/tables/array.py", line 662, in __getitem__
    arr = self._read_slice(startl, stopl, stepl, shape)
  File "/usr/local/lib/python3.5/dist-packages/tables/array.py", line 766, in _read_slice
    self._g_read_slice(startl, stopl, stepl, nparr)
  File "tables/hdf5extension.pyx", line 1585, in tables.hdf5extension.Array._g_read_slice
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 216, in H5Dread
    can't read data
  File "H5Dio.c", line 587, in H5D__read
    can't read data
  File "H5Dchunk.c", line 2304, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 3659, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1279, in H5Z_pipeline
    filter returned failure during read
  File "hdf5-blosc/src/blosc_filter.c", line 254, in blosc_filter
    Blosc decompression error

End of HDF5 error back trace
```
Training is still going on, but the loss is minus.

**Comment by gatagat** [comment]
@378978764 this still seems like some multi-threading issue (see https://pytables-users.narkive.com/6NhQIxKk/blosc-decompression-error-when-reading-table), if you prefer not to compile a thread-safe version of hdf5 from source, then here's some info how to make multi-threading work with pytables: http://www.pytables.org/latest/cookbook/threading.html

**Comment by xiaoxiaofeixiang** [comment]
> > see [keras-team/keras#8225](https://github.com/keras-team/keras/issues/8225)
> > set workers=0 to fit_generator, then error disappear, but then only one gpu is running
> 
> Where is the specific setting, I did not find it, can you help me?

training中有一个model.fit_generator()在里面添加 workers=0
