### ISSUE TITLE
Error Running

### ISSUE THREAD

**Issue by eddyrene** [ellisdg/3DUnetCNN#62]
Hello, i tried running the program 

![image](https://user-images.githubusercontent.com/10170394/33519450-beac27e2-d774-11e7-8c4b-d460c872eeda.png)

but I got this 

![image](https://user-images.githubusercontent.com/10170394/33519445-a69afcd2-d774-11e7-9fb6-5799a68fd543.png)

I installed all the dependencies, thank you

**Comment by mingrui** [comment]
4. Add the repository directory to the PYTONPATH system variable:

$ export PYTHONPATH=${PWD}:$PYTHONPATH

**Comment by eddyrene** [comment]
Thank you @mingrui,  now is working, Now I am running::

![image](https://user-images.githubusercontent.com/10170394/33529538-2c04e7d6-d840-11e7-873e-faaa08f9c681.png)

And it has run for more than 3 hours and just processes  38 directories of the type **TCGA-02-000X**  from the GBM directory and in total are 102 directories.

I am using a computer 
Intel® Core™ i5-6200U CPU @ 2.30GHz × 4,
GeForce 930MX/PCIe/SSE2  2GB 
and 8GB ram 
**I don't know if this process takes a long time?** 

I think that TF is working correctly with Nvidia card because 

![image](https://user-images.githubusercontent.com/10170394/33529612-2c4526b0-d841-11e7-813a-37ae32be8c89.png)

**Comment by eddyrene** [comment]
thank you @mingrui for your answer, but when I start the training get this :

![image](https://user-images.githubusercontent.com/10170394/33801840-ffe2dfbe-dd35-11e7-9be0-c378f8a030c2.png)

I don't know how to resolve this.

**Comment by mingrui** [comment]
looks like you are using tendorflow
set keras to use the ani as backend

**Comment by eddyrene** [comment]
@mingrui,  I finally train the CNN but when I run: **python predict.py** , another error appears, 

![image](https://user-images.githubusercontent.com/10170394/33813573-9bbf9af0-ddf2-11e7-9ceb-8bd6491bb45f.png)

Excuse me if I have become annoying

**Comment by shaniceC** [comment]
Hello. I am having the same problem as the original post but I still get the error even though I did step 4.

Thank you

**Comment by eddyrene** [comment]
@shaniceC , Have you refering to : export PYTHONPATH=${PWD}:$PYTHONPATH

Here is where you need to do 4 step : 
![image](https://user-images.githubusercontent.com/10170394/33922578-b89859e8-df99-11e7-9223-8a5100f737f8.png)

After that you can do :  cd brats

 and continue...

**Comment by shaniceC** [comment]
I do that and then after entering "from preprocess import convert_brats_data" 

I get "from: can't read /var/mail/preprocess"

**Comment by Ahgni** [comment]
hello,
I'm confused that if the ANTs must be installed?
Because my OS is Windows10, it's complicated to install.

**Comment by eddyrene** [comment]
Hello Ahgni, I think that you could use a docker to work, I recommend you a linux container enviroment.
