### ISSUE TITLE
Training on whole image

### ISSUE THREAD

**Issue by mingrui** [ellisdg/3DUnetCNN#63]
Has anyone tried training on the whole image? (Set patches to None)
My `dice_coef: 1.5921e-04` is really low.

**Comment by qitong** [comment]
same problem when train on whole image (patch_size = None)

**Comment by alkamid** [comment]
Does it work well when you train on patches?

**Comment by ellisdg** [comment]
Hey guys, I uploaded my results and they are now displayed in the [README](https://github.com/ellisdg/3DUnetCNN). My graphics card configuration doesn't have enough memory to do whole image training using the original UNet model. But I was able to do whole image training using a different [model architecture](https://github.com/ellisdg/3DUnetCNN/blob/master/unet3d/model/isensee2017.py). This gave me much better results than the patch-wise training using the original model.

**Comment by mingrui** [comment]
Will test new model architecture, thank you!
