### ISSUE TITLE
Version of TF and Keras

### ISSUE THREAD

**Issue by arielluluh** [ellisdg/3DUnetCNN#66]
Hi, I was using the code you provided several months ago. But there are some error shows like:
>>> runfile('/home/lhuang/Documents/Lhuang/BRATS/3DUnetCNN-master/brats/train.py', wdir='/home/lhuang/Documents/Lhuang/BRATS/3DUnetCNN-master/brats')
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)
  File "/home/lhuang/Documents/Lhuang/BRATS/3DUnetCNN-master/brats/train.py", line 56, in <module>
    main(overwrite=False)
  File "/home/lhuang/Documents/Lhuang/BRATS/3DUnetCNN-master/brats/train.py", line 38, in main
    initial_learning_rate=config["initial_learning_rate"])
  File "/home/lhuang/Documents/Lhuang/BRATS/3DUnetCNN-master/unet3d/model.py", line 29, in unet_model_3d
    conv1 = Conv3D(int(32/downsize_filters_factor), (3, 3, 3), activation='relu', padding='same')(inputs)
TypeError: __init__() takes at least 5 arguments (4 given)
--------------------------------------------------------------------------------------------------------------------------
It seems is the version problem. May I know what version of TF and Keras should be used for your previous code?

**Comment by ellisdg** [comment]
Have you tried using Python 3? I am using a few different versions of Keras & Tensorflow on different machines, but I do use Python 3. My local machine is using ```Keras 2.0.6``` and ```Tensorflow 1.2.1```.

**Comment by arielluluh** [comment]
Thank you. I found my tensorflow was too old. Now it works after I upgraded tensorflow.
