### ISSUE TITLE
Running testing.py

### ISSUE THREAD

**Issue by build2create** [ellisdg/3DUnetCNN#7]
Will be this be correct way to the `testing.py`
```
if __name__ == '__main__':
    run_test_case(0,"./data_test")
```

where `./data_test` is the name to the `out_dir` where the `prediction.nii.gz` should I also call `predict_from_data_file_and_write_image` from `run_test_case()` to actually write the image?

**Comment by ellisdg** [comment]
@build2create sorry, I hadn't tested that code out yet. With the latest commit that I just committed, you should be able to run the code as you have it in your comment.

**Comment by build2create** [comment]
Alright!

**Comment by build2create** [comment]
With the pre-trained model given [here](https://github.com/ellisdg/3DUnetCNN/issues/8) I generated `training_ids.pkl `and` testing_ids.pkl. `Bascially just to get testing ids required to test the model. I defined main class as : 
```
def main():
    run_test_case(1,"./data_test")
```

The problem is it is not producing any `data_dir` .Neither it is appending to it if I create one. @ellisdg  any idea on this one? Apologies for the constant trouble.

**Comment by ellisdg** [comment]
Maybe try giving a full path name instead of "./data_test"? Does that work?

**Comment by build2create** [comment]
Nope, it did not work

**Comment by ellisdg** [comment]
There are no error messages? Are you sure it is running? Have you tried a
debugger?

**Comment by build2create** [comment]
I am getting index error. Please see updated comment

**Comment by build2create** [comment]
In case you are not able to see I am reposting it here:
Initially I was getting this:
`ValueError: "concat" mode can only merge layers with matching output shapes except for the concat axis. Layer shapes: [(None, 1024, 18, 18, 9), (None, 256, 18, 18, 18)]`
then I updated the configuration in keras.json file as
```

{
"image_dim_ordering": "th",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "tensorflow"
}

```
Note: earlier"backend": "theano" this was the in the keras.json file so it was giving error.([refer this](https://github.com/orobix/retina-unet/issues/6))
it ran finally but gave error:
`ValueError: Invalid objective: dice_coef_loss
`
then I added these:
```
from model import dice_coef_loss
from model import dice_coef
```
and
`model = load_model(config["model_file"],custom_objects={'dice_coef_loss': dice_coef_loss,'dice_coef':dice_coef})
`
Now I get this error:

`ValueError: Error when checking : expected input_1 to have 5 dimensions, but got array with shape (3, 144, 144, 144)`
So in config.py I added 'T2' to config["training_modalities"]
Now to the call in main:
`run_test_case(1,'/home/adminsters/Desktop/3DUnetCNN-master/data_dir');`
it gives index error:
```
  File "testing.py", line 67, in <module>
    run_test_case(1,'/home/adminsters/Desktop/3DUnetCNN-master/data_dir');
  File "testing.py", line 53, in run_test_case
    image = nib.Nifti1Image(test_data[i], affine)
IndexError: index 3 is out of bounds for axis 0 with size 3
```

My testing_ids.pkl is:
`[141, 20, 15, 57, 186, 167, 60, 80, 23, 54, 143, 158, 132, 83, 61, 81, 168, 85, 157, 90, 147, 86, 127, 199, 74, 136, 24, 182, 146, 152, 170, 44, 30, 156, 172, 154, 1, 25, 59, 45]`

I guess it is because I changed the` config["training_modalities"]`
@ellisdg how to fix this Index error?

**Comment by ellisdg** [comment]
It looks like you may have modified line [53](https://github.com/ellisdg/3DUnetCNN/blob/master/testing.py#L53), or you may not have the latest version of the file.

**Comment by build2create** [comment]
Ok my bad, ran the updated code this time.
I got his output : 
![image](https://cloud.githubusercontent.com/assets/25721143/25301595/219251ba-2749-11e7-87a8-0dd95880fda5.png)
for a test image id 20. How should I infer segmentation labels from this, which one is necrotic,edemic and so on? Like the one in [this](https://github.com/naldeborgh7575/brain_segmentation)
When I choose to open segmented image I get this:
![image](https://cloud.githubusercontent.com/assets/25721143/25301629/d02a263a-2749-11e7-86a1-ddaf4b51fbb8.png)
Which patch is tumorous how should I interpret?

**Comment by ellisdg** [comment]
The image is a scalar image and not a label map. You need to view it in
grayscale as a scalar image.

**Comment by build2create** [comment]
Can you elaborate? The first screenshot shows grayscale image. Is that correct?How do I read the first image?Is it like darker parts tumorous?   Can you cite/give an example?

**Comment by build2create** [comment]
If I have understood it right this is not for tumor detection but just for volumetric segmentation right?

**Comment by build2create** [comment]
For FLAIR modality I am sort of getting evidently slightly more greyish patch, Is that the tumor?

**Comment by ellisdg** [comment]
T1:
![t1](https://cloud.githubusercontent.com/assets/8558995/25342535/f0ecf68e-28d1-11e7-8335-90dfe679086d.png)
T1c:
![t1c](https://cloud.githubusercontent.com/assets/8558995/25342569/04498d0a-28d2-11e7-9375-7e2ac18fcf93.png)
FLAIR:
![flair](https://cloud.githubusercontent.com/assets/8558995/25342576/0ba4404a-28d2-11e7-93cf-f365dcd238c3.png)
Tumor prediction. Ranges from 0 to 1:
![prediction](https://cloud.githubusercontent.com/assets/8558995/25342654/3fab180a-28d2-11e7-8735-4cbdd6986f4d.png)
Manual segmentation. The separate tumor regions are not used by the classifier:
![truth](https://cloud.githubusercontent.com/assets/8558995/25342687/5a54ddb2-28d2-11e7-848e-83e7e0a983dd.png)

**Comment by build2create** [comment]
Thanks. By the way which tool are you using for viewing? Is it ITK sanp?

**Comment by ellisdg** [comment]
[3D Slicer](https://www.slicer.org/). I know a lot of people use ITK Snap, but I've never taken the time to learn how to use it. 3D Slicer has a lot of features, so there might be a little bit of a learning curve. They also have plenty of helpful tutorials too.

**Comment by build2create** [comment]
Thanks a lot!

**Comment by build2create** [comment]
By volumetric segmentation we are detecting the presence or absence of the tumor but not the different segments within the tumor, like necrotic, core or enhancing. Doing this would be a multi-class classification problem right?

**Comment by build2create** [comment]
By volumetric segmentation we are detecting the presence or absence of the tumor but not the different segments within the tumor, like necrotic, core or enhancing. Doing this would be a multi-class classification problem right?

**Comment by build2create** [comment]
Also why are we not able to segment the tumor into sub-parts.Is it because of data set?I viewed ground truth of BRATS dataset in mha format. They do provide all the segmentation labels.

**Comment by ellisdg** [comment]
You should be able to train a classifier to segment different tumor regions with Keras. However, I currently have no need for multi-class labels, so I have [not implemented it yet.](https://github.com/ellisdg/3DUnetCNN/blob/master/generator.py#L62-L65) I will probably add this eventually, but that could be months from now.

**Comment by mingrui** [comment]
for anyone coming from the future, testing.py was renamed to predict.py:

https://github.com/ellisdg/3DUnetCNN/commit/b4012bb0b74dc7c48aa468fc0d277f5f0e374720#diff-22508acf6c6356eb94fbcda75eaf09f2
