### ISSUE TITLE
What is the exact output shape for this network

### ISSUE THREAD

**Issue by poornasandur** [ellisdg/3DUnetCNN#72]
Hi 
     What is the exact output shape for this network ? I am getting (44,44,62)...

**Comment by ellisdg** [comment]
The output shape should be (n_labels, image_size_x, image_size_y, image_size_z). So if you are using 64 cube patches and 3 labels. the output shape would be (3, 64, 64, 64).

**Comment by poornasandur** [comment]
Thanks for the input ..Sir...
