### ISSUE TITLE
 preprocessing is not working -> convert_brats_data("data/original", "data/preprocessed")

### ISSUE THREAD

**Issue by devareddy** [ellisdg/3DUnetCNN#76]
Hi, 
While i am running the preprocessing, "convert_brats_data("data/original", "data/preprocessed")" command is executing without  processing the data.
Your  help is highly appreciated!!

-D
>>> from preprocess import convert_brats_data
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
>>> convert_brats_data("/home/user/bratsfull/data/original", "/home/user/bratsfull/data/preprocessed")
>>> convert_brats_data("/home/user/bratsfull/data/original", "/home/user/bratsfull/data/preprocessed")

**Comment by ellisdg** [comment]
My guess would be that it isn't finding any of the subject folders. It assumes that a single subject folder in the "original" data folder to have this sort of structure:
```original/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/TCGA-02-0011```
If the data does not have that structure, it will just return without doing anything. Does your data have this structure?

**Comment by devareddy** [comment]
Hi, 
Changing  the path really helped me to run file.
Thanks a lot for your observation. 
But this leading to "truth_name" issue.
But in Brats17, Am unable to find the corresponding files for preprocessing.
 >>> convert_brats_data("data/original", "data/preprocessed")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "preprocess.py", line 164, in convert_brats_data
    no_bias_correction_modalities=no_bias_correction_modalities)
  File "preprocess.py", line 138, in convert_brats_folder
    truth_file = get_image(in_folder, truth_name.split("_")[0])
  File "preprocess.py", line 102, in get_image
    raise RuntimeError("Could not find file matching {}".format(file_card))
RuntimeError: Could not find file matching data/original/LGG/Brats17_2013_0_1/*GlistrBoost*.nii.gz

Your help is highly appreciated.
-D

**Comment by devareddy** [comment]
Hi,
Changing the path really helped me to run file.
Thanks a lot for your observation.
But this leading to "truth_name" issue.
            convert_brats_data("data/original", "data/preprocessed")
            Traceback (most recent call last):
            File "", line 1, in
            File "preprocess.py", line 164, in convert_brats_data
            no_bias_correction_modalities=no_bias_correction_modalities)
            File "preprocess.py", line 138, in convert_brats_folder
            truth_file = get_image(in_folder, truth_name.split("_")[0])
            File "preprocess.py", line 102, in get_image
            raise RuntimeError("Could not find file matching {}".format(file_card))
            RuntimeError: Could not find file matching data/original/LGG/Brats17_2013_0_1/GlistrBoost.nii.gz

But in Brats17, Am unable to find the corresponding files for preprocessing.
According to documentation segmentation labels are represented in *.seg.nii.gz files.
Can i use the above files?
If so how ?

Your help is highly appreciated.
-D

**Comment by CloudChoSony** [comment]
I had similar Runtime Error. For my case was "RuntimeError: Could not find file matching data/original/Pre-operative_TCGA_GBM_NIfTI_and_Segmentations/TCGA-06-0164/*t1.nii.gz"

I bypass the error by removing both original and preprocessed folders of TCGA-06-0164. 

This action makes me run train.py file but I have another error 'Floating point exception (core dumped)' after this action and I am still investigating.
