### ISSUE TITLE
Trained UNET model file

### ISSUE THREAD

**Issue by hawkeyedesi** [ellisdg/3DUnetCNN#77]
Hi David, 
Thanks for sharing your code. I am interested in doing a transfer learning off a pre-trained 3D UNET. Can you share you UNET model trained on the BRATS dataset? 

Thanks

**Comment by ellisdg** [comment]
Links to my trained Keras models are now available at the bottom of the [README](https://github.com/ellisdg/3DUnetCNN/blob/master/README.md) file.

**Comment by hawkeyedesi** [comment]
Perfect. Thanks.

**Comment by yvonnayunli** [comment]
@ellisdg, can you please also share the configuration you used to get these results? It might even have to do with the training/validation split because when I tried to train the two variants of the unets, I did not get the same level of performance.
