### ISSUE TITLE
Unknown layer: InstanceNormalization

### ISSUE THREAD

**Issue by chenypic** [ellisdg/3DUnetCNN#78]
Dear @ellisdg  thank you very much for sharing your code work. The train_isensee2017.py is running smoothly. After that, I want to run the predict.py, then an error occurred like this,
 "ValueError: Unknown layer: InstanceNormalization"

I have tried to find out a solution but I can't make it right. Could you please suggest me a way to solve this error.

Thanks in advanced

**Comment by ellisdg** [comment]
The issue should be fixed now. You will have to install [keras-contrib](https://github.com/keras-team/keras-contrib):
```pip install git+https://www.github.com/keras-team/keras-contrib.git```
