### ISSUE TITLE
Running the code in GPU

### ISSUE THREAD

**Issue by build2create** [ellisdg/3DUnetCNN#8]
Hello @ellisdg I would like to know your thoughts on following:
My system has following memory capabilities, output of `sudo lshw -class memory`
```
 *-memory
       description: System Memory
       physical id: 19
       slot: System board or motherboard
       size: 32GiB

```
Output of `nvidia-smi`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 745     Off  | 0000:01:00.0     Off |                  N/A |
| 25%   56C    P0    N/A /  N/A |   3701MiB /  4042MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
```
                                                                               
I ran keras functions with theano backend enabled and with GPU support with cnmem disabled,[setting it to higher values was giving memory errors](https://github.com/fchollet/keras/issues/987) Following are the things I tried:
a) 200 samples on theano backend with GPU enabled  but gives memory error. Following is the message
```
Creating validation split...
Epoch 1/50
Error allocating 37345632 bytes of device memory (out of memory). Driver report 4915200 bytes free and 4238540800 bytes total 

```
b)Reduced the size of `config["image_shape"]` from 144X144X144  to 80X80X80 and again got memory error
`Error allocating 7077888 bytes of device memory (out of memory). Driver report 1114112 bytes free and 4238540800 bytes total 
`
c)Reduced the data set size to 100 patients again got memory error
d)Now frustrated at this point, I disabled the GPU and re-ran with 100 samples and `config["image_shape"]` with 80X80X80 ,finally it runs fine
e) That gave a hope, so switched back to 200 patients with `config["image_shape"]`=(144,144,144) on CPU only but then every epoch is taking quite long to finish to be precise approximately 2 iterations of an epoch in one hour,by that rate it might take around 2 days for 1 epoch to finish. So 100 days for 50 epochs! That's quite a lot of time! 

```
Epoch 1/50
  1/160 [..............................] - ETA: 275472s - loss: -0.0516 - dice_c  2/160 [..............................] - ETA: 272867s - loss: -0.0491 - dice_c  3/160 [..............................] - ETA: 270868s - loss: -0.0554 - dice_c  4/160 [..............................] - ETA: 268988s - loss: -0.0727 - dice_c  5/160 [..............................] - ETA: 267151s - loss: -0.0688 - dice_c  6/160 [>.............................] - ETA: 265368s - loss: -0.0774 - dice_c  7/160 [>.............................] - ETA: 263591s - loss: -0.0894 - dice_coef: 0.0894                     

```
I looked [this](https://github.com/fchollet/keras/issues/141) but already we had `config["batch_size"] = 1`. Also I reduced the config["image_shape"] = (80,80,80) but no use. When I referred paper again I saw  they used Caffe and CuDNN. I believe their GPU has larger memory capabilities.

Will it be possible for you to upload trained model?

**Comment by ellisdg** [comment]
[Here is a pretrained model](https://www.dropbox.com/s/jraiykh3yqbgjqr/3d_unet_model.h5?dl=0)!

Yeah, I wonder if Caffe is better with handling larger datasets. I know that the authors of the 3D UNet paper have some sort of Matlab code for Caffe that you can download on [this page](https://lmb.informatik.uni-freiburg.de/resources/opensource/unet.en.html). Though, I don't know how to implement it.

**Comment by build2create** [comment]
Thanks for the model. This model is generated after 50 epochs right?

**Comment by ellisdg** [comment]
It's the model that produced the best validation score. I don't know which
epoch it is from though.
