### ISSUE TITLE
How to run test code

### ISSUE THREAD

**Issue by huanzhou94** [ellisdg/3DUnetCNN#81]
hi,

Thanks for the great work!

I have one query regarding to dataset split, I'm not sure if the datasets used for validation also included in training process? Or that's two total unrelated parts, if that's so, can I consider validation as same as testing?

And after training process, if I want to use new datasets for testing, how can I run the code inside your test folder?

Thank you for your time, really appreciated!

Regards,
Zhou Huan

**Comment by ellisdg** [comment]
During training the validation is used to check the progress of the training after each epoch. The validation data is never trained on, but just used to validate that the training is successfully generating a good classifier.

The code inside the test folder is different. The code contains NoseTests that I wrote to ensure that the code in this repository is working as it should.

**Comment by crazyzhaozhaojun** [comment]
> hi,
> 
> Thanks for the great work!
> 
> I have one query regarding to dataset split, I'm not sure if the datasets used for validation also included in training process? Or that's two total unrelated parts, if that's so, can I consider validation as same as testing?
> 
> And after training process, if I want to use new datasets for testing, how can I run the code inside your test folder?
> 
> Thank you for your time, really appreciated!
> 
> Regards,
> Zhou Huan

Hello, have you solved the problem? Thank you!
