### ISSUE TITLE
ValueError: When using a generator for validation data, you must specify a value for `validation_steps`.

### ISSUE THREAD

**Issue by Joeng22** [ellisdg/3DUnetCNN#88]
Hi,
I followed the same steps as mentioned in https://github.com/ellisdg/3DUnetCNN ,to train the brat data set, but getting errors
"
 raise ValueError('When using a generator for validation data, '
ValueError: When using a generator for validation data, you must specify a value for `validation_steps`.
Closing remaining open files:/home/dolby/joe/timed/keras_unet_3d/3DUnetCNN/brats/brats_data.h5...done
"

Anything I missed??

Thanks and regards

**Comment by CloudChoSony** [comment]
Please, check the #86. I think you may have the zero validation_steps.
