### ISSUE TITLE
getting the data

### ISSUE THREAD

**Issue by sflender** [ellisdg/3DUnetCNN#89]
Hi @ellisdg, is there another way to get the BRATS 2017 GBM and LGG data? The box links are not working.

**Comment by liuyongqing** [comment]
Hi @ellisdg , i also can't download the data set, could you offer another download link! thank you ~

**Comment by ellisdg** [comment]
Here are the new box links:
* [GBM](https://app.box.com/shared/static/bpqo6uqmqinke5jkyhbik9va2uq8ky01.zip)
* [LGG](https://app.box.com/shared/static/pqkmy3zcvud2qxlx5poe458azb1dzj54.zip)

For future reference, here are the wiki pages where I found the box links to the segmentation data:
 * [GBM wiki](https://wiki.cancerimagingarchive.net/display/DOI/Segmentation+Labels+and+Radiomic+Features+for+the+Pre-operative+Scans+of+the+TCGA-GBM+collection) 
 * [LGG wiki](https://wiki.cancerimagingarchive.net/display/DOI/Segmentation+Labels+and+Radiomic+Features+for+the+Pre-operative+Scans+of+the+TCGA-LGG+collection)

It looks like the old box links had been deleted. The new box links could easily be obtained, though, from the wiki links above.

**Comment by sflender** [comment]
Thanks!
