### ISSUE TITLE
What is the correct way to install ANTs N4Bias?

### ISSUE THREAD

**Issue by godissaw** [ellisdg/3DUnetCNN#9]
I'm sorry I met an error not about your code but the environment. When I convert data, it shows
 "_**command 'N4BiasFieldCorrection' could not be found on host 
Interface N4BiasFieldCorrection failed to run.**_ "
First, I pip install nipype
Then, I cmake the ANTs with the resource code( the ITVK is also installed) like the link "https://brianavants.wordpress.com/2012/04/13/updated-ants-compile-instructions-april-12-2012/"
Third, I add the 'path/to/ants/bin' to the $PATH in profile. But it still not works.

**Comment by godissaw** [comment]
whats more，can i use the N4 in sitk to replace it in ants？Thanks very much

**Comment by ellisdg** [comment]
Yes, you can use the bias field correction in SimpleITK. That's how I had it setup in my code originally, but it seemed to take a bit longer.

Have you tried running **N4BiasFieldCorrection** from the command line? If the ANTs binaries are in the PATH, then you should be able to run any ANTs executable on the command line.

**Comment by godissaw** [comment]
um, in the command the N4BiasFieldCorrection works, maybe I forgot to install the python wrapper? I'll have a try

**Comment by godissaw** [comment]
Sorry, I failed again. 
Do you remember how you installed your ANTs,aha? Just cmake it and let it download the IKT itself?

**Comment by ellisdg** [comment]
The problem seems to be that when you are running the python script, the
ANTs bin directory is not in you PATH environmental variable. I think you
have ANTs installed correctly.

**Comment by godissaw** [comment]
hhh, you should be right, but I deleted it XD.
That's right, I will try it again.

**Comment by godissaw** [comment]
I succeeded to convert, but I came across another issues, lol.
This could be closed, thants a lot~~~
