### ISSUE TITLE
Segmentation on pre-trained models is not right

### ISSUE THREAD

**Issue by sabrinamusatian** [ellisdg/3DUnetCNN#96]
Hi,
First of all thank you for such a great work!
I run into a strange issue, when using the pre-trained Unet model for Brats dataset. The predict.py works, but the output is wrong. I attached all the files for one of the examples. Can you please help me and point out what may be causing this problem? I downloaded the models from your README and added them in train configs files
<img width="676" alt="2018-03-28 1 39 54" src="https://user-images.githubusercontent.com/14347098/37998889-2a619d32-3229-11e8-8325-fd07224cb52a.png">

[truth.nii.gz](https://github.com/ellisdg/3DUnetCNN/files/1854023/truth.nii.gz)
[data_t2.nii.gz](https://github.com/ellisdg/3DUnetCNN/files/1854024/data_t2.nii.gz)
[data_flair.nii.gz](https://github.com/ellisdg/3DUnetCNN/files/1854025/data_flair.nii.gz)
[data_t1ce.nii.gz](https://github.com/ellisdg/3DUnetCNN/files/1854026/data_t1ce.nii.gz)
[data_t1.nii.gz](https://github.com/ellisdg/3DUnetCNN/files/1854027/data_t1.nii.gz)
[prediction.nii.gz](https://github.com/ellisdg/3DUnetCNN/files/1854028/prediction.nii.gz)

**Comment by primentropy** [comment]
I got the similar problem about prediction. when I try my own dataset with label data( 0 for background and 1 for the target area), I revise the train.py code by changing config["labels"] = (1, 2, 4) to config["labels"] = (0,1) and corresponding data path. Both train.py and predict.py works well, but in the prediction folder I only get a whole "black image" without any predicting label. I believe I am making some mistakes but could not figure it out. Could anyone help me ?
Many thanks!

**Comment by ni-wei** [comment]
@primentropy Does it make sense to _**config["labels"] = (1)**_ instead of _**config["labels"] = (0,1)**_ for your dataset?

**Comment by CocoInParis** [comment]
I met the same problem as well...

**Comment by FannierPeng** [comment]
@primentropy @CocoInParis Have you solved this problem?

**Comment by ljljlj02** [comment]
same problem
