### ISSUE TITLE
Can this code use multi GPU to increase block size

### ISSUE THREAD

**Issue by liuyongqing** [ellisdg/3DUnetCNN#97]
Hi @ellisdg , Thank for your code, Now I can run your code in my dataset, and achieve a good result in some sense, the result on the whole image  and the  block size is 128*128*128(one Nvidia 1080 Ti GPU )is good, and  a overlaping windows result is bad.  However, my dataset's size is  512*512*(200~500) , I don't know whether I can use more than one  GPU to  increase the block size to bigger size? Do you  know the relationship between the  block size  and GPU memory need? thank you ~

**Comment by ellisdg** [comment]
You can add multiple GPUs and this will increase your memory limit. But
increasing the image size will probably take up more memory than you could
reasonably add. For instance a 128×128x128 image has 2,097,152 voxels. A
512x512x200 image has 52,428,800 voxels. By that calculation you would need
26 GPUs. So, if you haven't done so already, it is probably more worthwhile
to look into training using patches. That way you can keep your images full
size.

**Comment by liuyongqing** [comment]
Hi  @ellisdg , thanks for you answer, Now I successful to  two GPU to increase the image size to 144*144*144, and crop the image size to smaller,  I hope the next training result can achieve  best result, Thank you very much!

**Comment by acumino** [comment]
please tell how to use multiple gpu
