### ISSUE TITLE
about predict and evaluate.

### ISSUE THREAD

**Issue by wcfzl** [ellisdg/3DUnetCNN#98]
Thank you for you share,and I have download the pre-trained model and brats2017 dataset.

when I use predict.py :
`UserWarning:Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer.
  warnings.warn('Error in loading the saved optimizer `
but it  still generate the prediction file
And when I use evaluate.py:
` FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
= <class 'numpy.ndarray'>
Traceback (most recent call last):
  File "evaluate.py", line 66, in <module>
    main()
  File "evaluate.py", line 47, in main
    scores[score] = values[np.isnan(values) == False]
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`
I want to ask how can I solve the error?Thamk you! @ellisdg

**Comment by ellisdg** [comment]
Were you able to get this working?

**Comment by shashikale** [comment]
I have just started looking into this, so quite new. I am using pre-trained model mentioned in README.
when i issue predict.py from brats I'm getting an error that validation_ids.pkl no such file or dir?
Can you please shade some light? Want to see the prediction part before I deep dive.

**Comment by zhoutonxgue** [comment]
@shashikale I have the same problem as you and how do you  solve the problem"validation_ids.pkl no such file or dir", thank you very much and waiting for your reply~

**Comment by akhanss** [comment]
Hi @shashikale and @zhoutonxgue 
You must run preprocessing script to generate validation_ids.pkl or you need to prepare the file youself.
Best,
-Azam.

**Comment by zhoutonxgue** [comment]
@akhanss    I have trained the model and now I use the test dataset of BRATs2018,  I want to predict it, I don't know how to modify the code, only change the prediction.py?
