### ISSUE TITLE
The predicted results appear to be incorrect

### ISSUE THREAD

**Issue by connorchen** [ellisdg/3DUnetCNN#99]
hi @ellisdg 
I use LGG & GBM to generate training and validation data.
I use the pre-trained model provided. isensee_2017_model.h5 or tumor_segmentation_model.h5
I run the predict.py
But the prediction for tumors is not correct.

Are the pre-trained models you provided correct?

**Comment by alkamid** [comment]
@wcfzl Sorry, I didn't try, I trained it on a different dataset.

**Comment by connorchen** [comment]
Maybe I made a mistake, model trained form train_isensee2017.py give great result
